USE EMPRESANEW;

-- 34.
SELECT NOME + ', ' + APELIDO1 + ', ' + ISNULL(APELIDO2, '') AS EMPREGRADO,
	COALESCE(telefono1, telefono2, 'Desconocido'), NOMEDEPARTAMENTO, V.Matricula, V.Modelo, v.DataCompra
FROM EMPREGADO E
INNER JOIN DEPARTAMENTO D ON E.NumDepartamentoPertenece = D.NumDepartamento
INNER JOIN VEHICULO V ON E.NSS = V.NSS
WHERE DATEDIFF(yy, V.DataCompra, GETDATE()) > 4

-- 35.
SELECT * , (
	SELECT COUNT(*) FROM EDICIONCURSO_EMPREGADO EE
	WHERE EE.Codigo = C.Codigo AND EE.Numero = E.Numero
) AS TOT_EMP_ED
FROM CURSO C 
INNER JOIN EDICION E ON E.Codigo = C.Codigo
WHERE E.Lugar IN ('VIGO', 'PONTEVEDRA')


-- 36
SELECT CASE PROVINCIA
	WHEN 27 THEN 'LUGO'
	WHEN 36 THEN 'PONTEVEDRA'
	ELSE 'SE DESCONOCE'
	END AS PROVINCIA
, COUNT(*) AS EMPREGRADOS
FROM EMPREGADO
GROUP BY Provincia

-- 37.
SELECT E.NOME + ', ' + E.APELIDO1 + ', ' + ISNULL(E.APELIDO2, '') AS EMPREGRADO,
	CASE F.Parentesco
		WHEN 'MARIDO' THEN 'MARIDO: ' + F.Nome + ', ' + F.Apelido1
		WHEN 'MULLER' THEN 'MULLER: ' + F.Nome + ', ' + F.Apelido1
		ELSE 'NO TIENE MARIDO / MUJER'
	END
FROM EMPREGADO E 
LEFT JOIN FAMILIAR F ON F.NSS_empregado = E.NSS


-- 38
SELECT E.NOME + ', ' + E.APELIDO1 + ', ' + ISNULL(E.APELIDO2, '') AS EMPREGRADO,
	P.NomeProxecto, P.Lugar
FROM EMPREGADO E 
INNER JOIN EMPREGADO_PROXECTO EP ON E.NSS = EP.NSSEmpregado
INNER JOIN PROXECTO P ON P.NumProxecto = EP.NumProxecto
WHERE P.LUGAR NOT IN (
	SELECT LUGAR FROM PROXECTO P2
	INNER JOIN EMPREGADO_PROXECTO EP ON EP.NumProxecto = P2.NumProxecto
	WHERE EP.NSSEmpregado = E.NSS
)


-- 40

-- EMPREGADOS QUE NO TRABAJEN EN SU CIUDAD Y QUE VIVAN DONDE SE DESAROLLE 
-- UN PROYECTO 
SELECT NSS , E.Localidade, P.Lugar
FROM EMPREGADO E 
INNER JOIN EMPREGADO_PROXECTO EP ON EP.NSSEmpregado = E.NSS
INNER JOIN PROXECTO P ON P.NumProxecto = EP.NumProxecto
WHERE E.Localidade != P.Lugar AND
	E.Localidade IN (
		SELECT LUGAR FROM PROXECTO
	)

-- EMPLEADOS QUE VIVEN EN EL MISMO LUGAR QUE PROYECTOS
SELECT NSS , E.Localidade, P.Lugar
FROM EMPREGADO E 
INNER JOIN EMPREGADO_PROXECTO EP ON EP.NSSEmpregado = E.NSS
INNER JOIN PROXECTO P ON P.NumProxecto = EP.NumProxecto
WHERE E.Localidade = P.Lugar


-- 41

SELECT NSS , E.Localidade, P.Lugar, 40 - SUM(EP.HORAS) AS HORAS
FROM EMPREGADO E 
INNER JOIN EMPREGADO_PROXECTO EP ON EP.NSSEmpregado = E.NSS
INNER JOIN PROXECTO P ON P.NumProxecto = EP.NumProxecto
WHERE E.Localidade != P.Lugar AND
	E.Localidade IN (
		SELECT LUGAR FROM PROXECTO
	) AND HORAS > 10
GROUP BY NSS, Localidade, LUGAR
