USE CATASTRO;

-- 79
SELECT NOMBREZONA, ISNULL(OBSERVACIONES, 'NO HAY OBSERVACIONES')
FROM ZONAURBANA ZU

-- 80
SELECT DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2,
		ISNULL(V.NOMBREZONA, V2.NOMBREZONA) AS NOMBRE_ZONA, ISNULL(V.CALLE, V2.CALLE) AS CALLE
FROM PROPIETARIO PRO
LEFT JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
LEFT JOIN CASAPARTICULAR CP ON CP.DNIPROPIETARIO = PRO.DNI
LEFT JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
LEFT JOIN VIVIENDA V2 ON V2.CALLE = CP.CALLE AND V2.NUMERO = CP.NUMERO
ORDER BY RIGHT(ISNULL(V.NOMBREZONA, V2.NOMBREZONA), 2), CALLE

-- 81.
SELECT TOP 2 DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2, NEWID() AS ID
FROM PROPIETARIO PRO
ORDER BY ID DESC


-- 82. 
SELECT V.CALLE, V.NUMERO, PLANTA, PUERTA, NUMHABITACIONES, METROSUTILES, 
		PRO.NOMBRE, PRO.APELLIDO1,
		CASE P.NUMHABITACIONES
			WHEN 1 THEN 'APARTAMENTO'
			WHEN 2 THEN 'APARTAMENTO'
			WHEN 3 THEN 'PISO'
			WHEN 4 THEN 'PISO'
		ELSE 'PISAZO'
		END AS TIPO_PISO
		
FROM PISO P 
INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
INNER JOIN ZONAURBANA ZU ON ZU.NOMBREZONA = V.NOMBREZONA
WHERE ZU.NUMPARQUES > 1

--85

DECLARE @PISOS_HOMBRES INT
SELECT @PISOS_HOMBRES = COUNT(*)
FROM PROPIETARIO PRO
INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
WHERE SEXO = 'H'

DECLARE @PISOS_MUJERES INT
SELECT @PISOS_MUJERES = COUNT(*)
FROM PROPIETARIO PRO
INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
WHERE SEXO = 'M'

SELECT CASE 
	WHEN @PISOS_HOMBRES = @PISOS_MUJERES THEN  'MISMA CANTIDAD DE PISOS'
	WHEN @PISOS_HOMBRES > @PISOS_MUJERES THEN 'LOS HOMBRES TIIENEN MAS PISOS'
	ELSE 'LAS MUJERES TIENEN MAS PISOS'
	END
	
SELECT @PISOS_HOMBRES, @PISOS_MUJERES


-- 86.
SELECT DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2,
		'PISO' AS [TIPO PROPIEDAD]
FROM PROPIETARIO PRO
INNER JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI

UNION 

SELECT DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2,
		'VIVIENDA UNIFAMILIAR' AS [TIPO PROPIEDAD]
FROM PROPIETARIO PRO
INNER JOIN CASAPARTICULAR CP ON CP.DNIPROPIETARIO = PRO.DNI

UNION

SELECT DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2,
		'TRASTERO' AS [TIPO PROPIEDAD]
FROM PROPIETARIO PRO
INNER JOIN HUECO H ON H.DNIPROPIETARIO = PRO.DNI
WHERE TIPO = 'TRASTERO'

UNION

SELECT DNI , NOMBRE, APELLIDO1, ISNULL(APELLIDO2, '') AS APELLIDO2,
		'GARAJE' AS [TIPO PROPIEDAD]
FROM PROPIETARIO PRO
INNER JOIN HUECO H ON H.DNIPROPIETARIO = PRO.DNI
WHERE TIPO = 'GARAJE'


-- 87.
SELECT TOP 1 WITH TIES DNI , NOMBRE + ', ' + APELLIDO1 + ', ' + ISNULL(APELLIDO2, '') AS PROPIESTARIO,

	(
		SELECT COUNT(*) FROM PISO WHERE DNIPROPIETARIO = PRO.DNI
	) + 
		(
		SELECT COUNT(*) FROM CASAPARTICULAR WHERE DNIPROPIETARIO = PRO.DNI
	) + 
		(
		SELECT COUNT(*) FROM HUECO WHERE DNIPROPIETARIO = PRO.DNI
	) AS CONTEO
FROM PROPIETARIO PRO 
ORDER BY CONTEO DESC

-- 89
USE EMPRESANEW;

SELECT AVG(SALARIO)
FROM EMPREGADOFIXO


DECLARE @SUMATOTAL INT
SELECT @SUMATOTAL = (SUM(SALARIO) - MAX(Salario)) - MIN(SALARIO)
FROM EMPREGADOFIXO

SELECT @SUMATOTAL / (SELECT COUNT(*) -2 FROM EMPREGADOFIXO) AS MEDIA




