use master;

IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'NOMBRE_BASE')
	DROP DATABASE NOMBRE_BASE;
	
CREATE DATABASE NOMBRE_BASE
ON PRIMARY
(
	NAME='NOMBRE_BASE',
	FILENAME='C:\basedatos\Apuntes\ArchivoPrincipal.mdf',
	SIZE=3MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%
),
FILEGROUP GRUPOARCHIVOS1
(	
	NAME='NOMBRE_BASE2',
	FILENAME='C:\basedatos\Apuntes\ARCHIVOSECUNDARIO.Ndf',
	SIZE=3MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%
)
LOG ON
(	NAME='ARCHIVO_LOGS',
	FILENAME='C:\basedatos\Apuntes\ARCHIVO_LOGS.LDF',
	SIZE=3MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%
);


USE NOMBRE_BASE;

ALTER DATABASE NOMBRE_BASE MODIFY FILEGROUP GRUPOARCHIVOS1 DEFAULT;


ALTER DATABASE NOMBRE_BASE
ADD FILE
(
	NAME='NOMBRE_BASE3',
	FILENAME='C:\basedatos\Apuntes\ARCHIVOSECUNDARIO2.Ndf',
	SIZE=3MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%
)
	
