use CATASTRO

IF OBJECT_ID('prPropietarioPiso ') IS NOT NULL 
	OR OBJECT_ID('fnPropietarioPiso ') IS NOT NULL
BEGIN 
DROP PROCEDURE prPropietarioPiso
--DROP FUNCTION fnPropietarioPiso
END

GO
CREATE PROCEDURE prPropietarioPiso
	(@CALLE VARCHAR(100),@NUMERO VARCHAR(100),@PLANTA VARCHAR(100),@PUERTA VARCHAR(100), 
		@NOMBREOT VARCHAR(100) OUTPUT)
AS
BEGIN 
SET NOCOUNT ON
	IF (@CALLE NOT IN (SELECT CALLE FROM PISO))
		RETURN -1
	IF (@NUMERO NOT IN (SELECT NUMERO FROM PISO
						WHERE CALLE=@CALLE))
		RETURN -2
	IF @PLANTA NOT IN (SELECT PLANTA FROM PISO
						WHERE NUMERO=@NUMERO AND CALLE=@CALLE) 
		RETURN -3
	IF @PUERTA NOT IN (SELECT PUERTA FROM PISO
						WHERE NUMERO=@NUMERO AND CALLE=@CALLE
							AND PLANTA=@PLANTA) 
		RETURN -4
	
	SELECT @NOMBREOT = 
	NOMBRE+ ' ' + APELLIDO1 + ' ' + ISNULL(APELLIDO2, '')
	FROM PROPIETARIO PRO
	INNER JOIN PISO ON PRO.DNI = PISO.DNIPROPIETARIO
	WHERE CALLE = @CALLE AND NUMERO = @NUMERO AND @PLANTA = PLANTA
			AND @PUERTA = PUERTA
						
END

GO
DECLARE @NOMBRE VARCHAR(50)
EXEC prPropietarioPiso 'Alegria', 44, 1, 'A', @NOMBRE OUTPUT
SELECT @NOMBRE

GO

IF OBJECT_ID('fnPropietarioPiso ') IS NOT NULL
BEGIN 
DROP FUNCTION fnPropietarioPiso
END

GO
CREATE FUNCTION fnPropietarioPiso
	(@CALLE VARCHAR(100),@NUMERO VARCHAR(100),
		@PLANTA VARCHAR(100),@PUERTA VARCHAR(100))
RETURNS VARCHAR(100)
BEGIN
	
	DECLARE @NOMBREOT VARCHAR(100)
	
	IF (@CALLE NOT IN (SELECT CALLE FROM PISO))
		RETURN -1
	IF (@NUMERO NOT IN (SELECT NUMERO FROM PISO
						WHERE CALLE=@CALLE))
		RETURN -2
	IF @PLANTA NOT IN (SELECT PLANTA FROM PISO
						WHERE NUMERO=@NUMERO AND CALLE=@CALLE) 
		RETURN -3
	IF @PUERTA NOT IN (SELECT PUERTA FROM PISO
						WHERE NUMERO=@NUMERO AND CALLE=@CALLE
							AND PLANTA=@PLANTA) 
		RETURN -4
	
	SELECT @NOMBREOT =   
	NOMBRE+ ' ' + APELLIDO1 + ' ' + ISNULL(APELLIDO2, '')
	FROM PROPIETARIO PRO
	INNER JOIN PISO ON PRO.DNI = PISO.DNIPROPIETARIO
	WHERE CALLE = @CALLE AND NUMERO = @NUMERO AND @PLANTA = PLANTA
			AND @PUERTA = PUERTA
	
	RETURN @NOMBREOT

END

GO
SELECT dbo.fnPropietarioPiso('Alegria', 99, 1, 'A') as propietario


GO
IF OBJECT_ID('prPisosTiene2') IS NOT NULL 
BEGIN 
--DROP PROCEDURE prPisosTiene1
DROP PROCEDURE prPisosTiene2
END


GO
CREATE PROCEDURE prPisosTiene2
	(@DNI VARCHAR(9), @CONTEO INT OUTPUT, @COD_ESTADO INT OUTPUT)
AS 
BEGIN 

	SET @CONTEO = 0

	IF (@DNI NOT IN (SELECT DNI FROM PROPIETARIO))
		SET @COD_ESTADO = -1
	IF (@DNI IS NULL)
		SET @COD_ESTADO = -2
	IF @DNI NOT IN (SELECT DNIPROPIETARIO FROM PISO)
		SET @COD_ESTADO = -3
	ELSE
		SET @COD_ESTADO = 4
		
	SELECT @CONTEO = COUNT(*) 
	FROM PISO P 
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
	
END

-- 


DECLARE @CONTEO2 INT
DECLARE @COD_ESTADO2 INT
EXEC prPisosTiene2 '88888822H', @CONTEO2 OUTPUT, @COD_ESTADO2 OUTPUT -- NO ESTA -1
SELECT @COD_ESTADO2

-- 1 

GO
IF OBJECT_ID('prPisosTiene1') IS NOT NULL 
BEGIN 
--DROP PROCEDURE prPisosTiene1
DROP PROCEDURE prPisosTiene1
END


GO
CREATE PROCEDURE prPisosTiene1
	(@DNI VARCHAR(9))
AS
BEGIN 

DECLARE @CONTEO INT
DECLARE @COD_ESTADO2 INT
EXEC prPisosTiene2 @DNI, @CONTEO OUTPUT, @COD_ESTADO2 OUTPUT

	IF @COD_ESTADO2 = -1
		print 'a'
		
	IF @COD_ESTADO2 = -2
		PRINT ''
		
	IF @COD_ESTADO2 = -3
		PRINT 'A'
		
	IF @COD_ESTADO2 = 4
		PRINT 'EL PROPIETARIO CON EL DNI: ' + @DNI + ' TIENE ' 
			+ cast(@CONTEO as varchar) + ' PISOS'
END

GO
EXEC dbo.prPisosTiene1 '88888822H'

select * from PISO where DNIPROPIETARIO = '88888822H'
