IF OBJECT_ID('DBO.PR_SUMN') IS NOT NULL
DROP PROCEDURE DBO.PR_SUMN;

GO
CREATE PROCEDURE PR_SUMN
@NUMERO INT, @SUMA INT OUTPUT
AS 
BEGIN
IF (@NUMERO < 0) RETURN -1
END


IF OBJECT_ID('DBO.MayorDeDosEnteros ') IS NOT NULL
DROP PROCEDURE DBO.MayorDeDosEnteros;
GO
 
CREATE PROCEDURE MayorDeDosEnteros
@N1 INT , @N2 INT
AS
BEGIN 
IF @N1 = @N2 PRINT 'SON IGUALES'
IF @N1 > @N2 
	PRINT @N1 + ' ES MAYOR QUE ' + @N2
ELSE
	PRINT @N2 + ' ES MAYOR QUE ' + @N1
	
END

EXEC MayorDeDosEnteros 9,9
