USE EMPRESANEW;

ALTER TABLE EMPREGADO
	ADD NUM_PROXECTOS INT NULL

GO
IF OBJECT_ID('pr_ActulizarNumpro') IS NOT NULL
	DROP PROCEDURE pr_ActulizarNumpro

GO
CREATE PROCEDURE pr_ActulizarNumpro
	@NSS VARCHAR(15), @NUM_PROXECTOS INT OUTPUT 
AS
SET NOCOUNT ON 
BEGIN

	IF @NSS NOT IN (SELECT NSS FROM EMPREGADO)
		RETURN -1
	ELSE 
		RETURN 0
		
	SELECT @NUM_PROXECTOS = COUNT(*)
	FROM EMPREGADO_PROXECTO EP
	WHERE EP.NSSEmpregado = @NSS
	
	UPDATE EMPREGADO
	SET NUM_PROXECTOS = @NUM_PROXECTOS
	WHERE NSS = @NSS
END

GO
IF OBJECT_ID('pr_ActualizarTodosNumpro') IS NOT NULL
	DROP PROCEDURE pr_ActualizarTodosNumpro
	
GO
CREATE PROCEDURE pr_ActualizarTodosNumpro
AS 
SET NOCOUNT ON 
BEGIN
	
	DECLARE CURSOR1 CURSOR DYNAMIC FOR
	SELECT NSS FROM EMPREGADO
	
	DECLARE @NSS VARCHAR(15)
	DECLARE @NOME VARCHAR (300)
	DECLARE @NUM_PRO TINYINT 
	
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @NSS
	WHILE (@@FETCH_STATUS <> -1 )
		IF (@@FETCH_STATUS = -2)
		BEGIN
			FETCH NEXT FROM CURSOR1 INTO @NSS
			CONTINUE
		END
		
	EXEC pr_ActulizarNumpro @NSS, @NUM_PRO OUTPUT
	
	CLOSE CURSOR1
	DEALLOCATE CURSOR1
	
	
	
	
END

GO

IF OBJECT_ID('pr_CrearEdicion') IS NOT NULL
	DROP PROCEDURE pr_CrearEdicion
	
GO

CREATE PROCEDURE pr_CrearEdicion
	(@CURSO INT, @LUGAR VARCHAR(100) = NULL, @FECHA DATE = NULL, @PROFESOR VARCHAR(15))
AS 
SET NOCOUNT ON 
BEGIN
	
	IF @CURSO NOT IN (SELECT CODIGO FROM CURSO)
		RETURN -1
	IF @PROFESOR NOT IN (SELECT NSS FROM EMPREGADOFIXO)
		RETURN -2
		
	DECLARE @ULT_EDICION INT 
	SELECT @ULT_EDICION = MAX(NUMERO) 
	FROM  EDICION
	WHERE Codigo = @CURSO
	
	DECLARE @FECHA2 DATE 
	IF (@FECHA IS NULL)
	-- FALTA TERMINAR CADA VARAIBLE 
	-- SI ES NUL FECHA Y LUGAR
	
	IF (@FECHA IS NULL)
	BEGIN
		INSERT INTO EDICION
		VALUES (@CURSO, @ULT_EDICION +1, DATEADD(MM, +1 , GETDATE()),
					@LUGAR, @PROFESOR )
	END

	
END 

