USE CATASTRO

IF OBJECT_ID('EJERCICIO1') IS NOT NULL
	DROP PROCEDURE EJERCICIO1

GO
CREATE PROCEDURE EJERCICIO1 
AS BEGIN 

	DECLARE EJERCICIO1_CURSOR CURSOR 
	LOCAL FORWARD_ONLY STATIC FOR
	SELECT DNI FROM PROPIETARIO
	
	DECLARE @DNIPROPI CHAR(9)
	
	OPEN EJERCICIO1_CURSOR
	FETCH NEXT FROM EJERCICIO1_CURSOR INTO @DNIPROPI
END


EXEC EJERCICIO1