USE CATASTRO;
IF OBJECT_ID('PRLISTARPROPIEDADES') IS NOT NULL
	DROP PROCEDURE PRLISTARPROPIEDADES


GO
CREATE PROCEDURE PRLISTARPROPIEDADES
AS
BEGIN
	
	DECLARE @DNIPROPIETARIO CHAR(9)
	DECLARE @NOMBREPROPIETARIO VARCHAR(50)
	
	PRINT('LISTADO DE PROPIETARIOS')
	
	DECLARE CURSORPROPIETARIO CURSOR STATIC FOR
	SELECT DNI, NOMBRE + ' ' + APELLIDO1 FROM PROPIETARIO
	
	OPEN CURSORPROPIETARIO
	FETCH NEXT FROM CURSORPROPIETARIO INTO @DNIPROPIETARIO, @NOMBREPROPIETARIO
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
	
		PRINT 'DNI PROPIETARIO: ' + @DNIPROPIETARIO + ' ' + @NOMBREPROPIETARIO
	

		EXEC PR_LISTAR_PISOS @DNIPROPIETARIO
		EXEC PR_LISTAR_VIVIENDAS @DNIPROPIETARIO
		EXEC PR_LISTAR_HUECOS @DNIPROPIETARIO
		
		PRINT '*******************************************************'
	
		FETCH NEXT FROM CURSORPROPIETARIO INTO @DNIPROPIETARIO, @NOMBREPROPIETARIO
	END
	
	CLOSE CURSORPROPIETARIO
	DEALLOCATE CURSORPROPIETARIO
	
END


-- AHORA LO QUE HAGO ES CREAR CADA PROCEDIMIENTO INDIVIDUAL
-- PARA TENER TODO MUCHO MAS ORDENADO
GO
IF OBJECT_ID('PR_LISTAR_PISOS') IS NOT NULL
	DROP PROCEDURE PR_LISTAR_PISOS
	
GO
CREATE PROCEDURE PR_LISTAR_PISOS
	(@DNI CHAR(9))
AS
BEGIN

		PRINT SPACE(30) + 'PISOS'
		PRINT '--------------------------------------------------------'
		PRINT 'CALLE'+SPACE(14)+ 'NUMERO'+SPACE(3) + 'PLANTA' +SPACE(3)
			+ 'NUMHABITACIONES' +SPACE(3) + 'METROSUTILES' +SPACE(3)
			+ 'METROSCONSTRUIDOS'
			
	DECLARE @CALLE VARCHAR(50)
	DECLARE @NUMERO INT
	DECLARE @PLANTA INT
	DECLARE @NUMHABITACIONES INT
	DECLARE @METROSUTILES INT
	DECLARE @METROSCONSTRUIDOS INT

	SELECT @CALLE=CALLE, @NUMERO=NUMERO, @PLANTA=PLANTA,
			@NUMHABITACIONES=NUMHABITACIONES, @METROSUTILES=METROSUTILES,
			@METROSCONSTRUIDOS=METROSCONSTRUIDOS			
	FROM PISO
	WHERE DNIPROPIETARIO = @DNI
	
	PRINT @CALLE+SPACE(14)+ CAST(@NUMERO AS VARCHAR(3))+SPACE(3) + 
			CAST(@PLANTA AS VARCHAR(3)) +SPACE(3)
			+ CAST(@NUMHABITACIONES AS VARCHAR(3)) 
			+SPACE(3) + CAST(@METROSUTILES AS VARCHAR(3)) +SPACE(3)
			+ CAST(@METROSCONSTRUIDOS AS VARCHAR(3))
	
END


-- VIVIENDAS UNIFAMILIARES 

GO
IF OBJECT_ID('PR_LISTAR_VIVIENDAS') IS NOT NULL
	DROP PROCEDURE PR_LISTAR_VIVIENDAS
	
GO
CREATE PROCEDURE PR_LISTAR_VIVIENDAS
	(@DNI CHAR(9))
AS
BEGIN

		PRINT SPACE(30) + 'VIVIENDA UNIFAMILIAR'
		PRINT '--------------------------------------------------------'
		PRINT 'CALLE'+SPACE(14)+ 'NUMERO'+SPACE(3) + 'NUM PLANTAS' +SPACE(3)
			+ 'PISCINA' +SPACE(3)+ 'METROSCONSTRUIDOS'
			
	DECLARE @CALLE VARCHAR(50)
	DECLARE @NUMERO INT
	DECLARE @PLANTA INT
	DECLARE @PISCINA CHAR(1)
	DECLARE @METROSCONSTRUIDOS INT

	SELECT @CALLE= CALLE, @NUMERO=NUMERO, @PLANTA=NUMPLANTAS,
			@PISCINA=PISCINA,
			@METROSCONSTRUIDOS=METROSCONSTRUIDOS			
	FROM CASAPARTICULAR
	WHERE DNIPROPIETARIO = @DNI
	
	PRINT @CALLE+SPACE(14)+ CAST(@NUMERO AS VARCHAR(3))+SPACE(3) + 
			CAST(@PLANTA AS VARCHAR(3)) +SPACE(3)
			+ @PISCINA
			+SPACE(3)
			+ CAST(@METROSCONSTRUIDOS AS VARCHAR(3))
	
END

GO
IF OBJECT_ID('PR_LISTAR_HUECOS') IS NOT NULL
	DROP PROCEDURE PR_LISTAR_HUECOS
	
GO
CREATE PROCEDURE PR_LISTAR_HUECOS
	(@DNI CHAR(9))
AS
BEGIN

		PRINT SPACE(30) + 'HUECOS'
		PRINT '--------------------------------------------------------'
		PRINT 'CALLE'+SPACE(14)+ 'NUMERO'+SPACE(3) + 'PLANTA' +SPACE(3)
			+ 'PUERTA' +SPACE(3)+ 'METROSCONSTRUIDOS'+ 
			SPACE(3)+ 'TIPO' + SPACE(3) + 'CODIGO'
			
	DECLARE @CALLE VARCHAR(50)
	DECLARE @NUMERO INT
	DECLARE @PLANTA INT
	DECLARE @PUERTA CHAR(1)
	DECLARE @METROSCONSTRUIDOS INT
	DECLARE @TIPO VARCHAR(50)
	DECLARE @CODIGO DECIMAL

	SELECT @CALLE= CALLE, @NUMERO=NUMERO, @PLANTA=PLANTA,
			@PUERTA=PUERTA,
			@METROSCONSTRUIDOS=METROS,
			@TIPO = TIPO,
			@CODIGO = CODIGO		
	FROM HUECO
	WHERE DNIPROPIETARIO = @DNI
	
	PRINT @CALLE+SPACE(14)+ CAST(@NUMERO AS VARCHAR(3))+SPACE(3) + 
			CAST(@PLANTA AS VARCHAR(3)) +SPACE(3)
			+ CAST(@METROSCONSTRUIDOS AS VARCHAR(3))
			+SPACE(3)
			+ @TIPO
			+SPACE(3)
			+ CAST(@CODIGO AS VARCHAR(10))
	
END




-- FIN PROCEDIMIENTOS 

EXEC PRLISTARPROPIEDADES


SELECT * FROM CASAPARTICULAR


-- EJERCICIO 2 
IF OBJECT_ID('BDMANETNIMIENTO') IS NOT NULL
	DROP DATABASE BDMANETNIMIENTO
	
GO
CREATE DATABASE BDMANETNIMIENTO
GO
USE BDMANETNIMIENTO
GO
CREATE PROCEDURE PR_BDMANETNIMIENTO
AS
BEGIN 

	SET NOCOUNT ON 
	
	DECLARE LOGIN_CURSOR CURSOR FOR
	SELECT NOMBRE, APELLIDO_1
	FROM EMPRESANEW.DBO.EMPLEADO
	
	OPEN LOGIN_CURSOR
	DECLARE @NOMBRE VARCHAR(50)
	DECLARE @APELLIDO1 VARCHAR(50)
	DECLARE @USUARIO VARCHAR(50)
	DECLARE @CLAVE VARCHAR(50)
	
	FETCH NEXT FROM LOGIN_CURSOR INTO @NOMBRE, @APELLIDO1
	WHILE @@FETCH_STATUS = 0	
	BEGIN 
		SET @USUARIO = LEFT(@NOMBRE,3) + LEFT(@APELLIDO1,3)
		SET @CLAVE = SUBSTRING(CAST(NEWID() AS VARCHAR(50)),1,12)
		
		-- PARA ESCAPAR LA  ' , ESCRIBIR FOS VECES '' : '''' (UA QIE ' ES UN
		-- CARACTER ESPECIAL PARA CONCATENAR STRING)
		EXECUTE ('CREATE LOGIN ' + @LOGIN + ' WITH PASSWORD='+'''' + 
			@CLAVE+''''+ 'MUST_CHANGE, CHECKEXPIRATION=ON')
			
		FETCH NEXT FROM LOGIN_CURSOR INTO @NOMBRE, @APELLIDO1
	END
	CLOSE LOGIN_CURSOR
	DEALLOCATE LOGIN_CURSOR
END

	
	
	



