USE SOCIEDADE_CULTURAL;

SELECT * FROM AULA

BEGIN TRANSACTION
BEGIN TRY

UPDATE AULA
SET superficie = superficie + 20,
	estado = 'B'
WHERE descricion = 'COCIÑA'

COMMIT 
END TRY
BEGIN CATCH 
	ROLLBACK
	PRINT 'ERROR'
END CATCH


-- 19
SET IMPLICIT_TRANSACTIONS ON 

DECLARE @COD_CARMEN INT
SELECT @COD_CARMEN = NUMERO
FROM SOCIO S 
WHERE nome = 'JOSE' AND ape1='DEL CARMEN' AND ape2='LÉREZ'

DECLARE @TIPO_CARMEN VARCHAR(30)
SELECT @TIPO_CARMEN = TIPO
FROM SOCIO WHERE numero = @COD_CARMEN

SELECT * FROM ACTIVIDADE
SELECT * FROM COTA

DECLARE @NUMERO_MAX INT = (SELECT MAX(NUMERO) FROM SOCIO)

INSERT INTO SOCIO
VALUES(@NUMERO_MAX ,'90897867B', NULL, 'PETER', 'SMITH', NULL, '690112233',
			NULL, '1990-02-19','RUA','PAZ','15',NULL,'A CORUÑA',
			'15444',NULL,@TIPO_CARMEN, NULL, 1, 13, @COD_CARMEN)
			
DECLARE @COD_PETER INT
SELECT @COD_PETER = NUMERO 
FROM SOCIO WHERE NIF = '90897867B'

INSERT INTO SOCIO_REALIZA_ACTI
VALUES (@COD_PETER, 99, 1)
COMMIT 
