USE EMPRESANEW;

-- 1.
DECLARE @CODMELLORASSOCIAIS INT
SELECT @CODMELLORASSOCIAIS = NumProxecto
FROM PROXECTO
WHERE NomeProxecto='MELLORAS SOCIAIS'

INSERT INTO EMPREGADO_PROXECTO
VALUES ('1122331', @CODMELLORASSOCIAIS, 3)

-- 2.
UPDATE EMPREGADOFIXO
SET Salario = NULL
FROM EMPREGADOFIXO EP
INNER JOIN EMPREGADO E ON E.NSS = EP.NSS
INNER JOIN DEPARTAMENTO D  ON E.NumDepartamentoPertenece = D.NumDepartamento
WHERE D.NomeDepartamento = 'INNOVACIÓN'

SELECT SALARIO
FROM EMPREGADOFIXO EP 
INNER JOIN EMPREGADO E ON E.NSS = EP.NSS
INNER JOIN DEPARTAMENTO D  ON E.NumDepartamentoPertenece = D.NumDepartamento
WHERE D.NomeDepartamento = 'INNOVACIÓN'


-- 3.
UPDATE EMPREGADOFIXO
SET Salario = 1900
FROM EMPREGADOFIXO EP
INNER JOIN EMPREGADO E ON E.NSS = EP.NSS
INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NumDepartamentoPertenece
WHERE E.NSS NOT IN (
	SELECT NSSDirector FROM DEPARTAMENTO D
) AND EP.Salario = NULL

SELECT EP.Salario
FROM EMPREGADOFIXO EP
INNER JOIN EMPREGADO E ON E.NSS = EP.NSS
INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NumDepartamentoPertenece
WHERE E.NSS NOT IN (
	SELECT NSSDirector FROM DEPARTAMENTO D
) AND EP.Salario NULL