USE CATASTRO;
-- 2 

BEGIN TRANSACTION 
BEGIN TRY

INSERT INTO PROPIETARIO 
VALUES ('32444423M', 'CLEMENTINA', 'ARES', 'GARCÍA', 'M', NULL)

UPDATE HUECO
SET DNIPROPIETARIO = '32444423M'
WHERE TIPO='GARAJE' 

COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH


-- 3.
USE EMPRESANEW;

DECLARE @COD_DEP_TEC INT
SELECT @COD_DEP_TEC = NUMDEPARTAMENTO 
FROM DEPARTAMENTO
WHERE NomeDepartamento='TÉCNICO'

DECLARE @ID_NEXT_LUGAR INT
SELECT TOP 1 @ID_NEXT_LUGAR =  ID 
FROM  LUGAR
ORDER BY ID DESC

INSERT INTO LUGAR
VALUES (@ID_NEXT_LUGAR+1, @COD_DEP_TEC, 'villagarcía')

SELECT * FROM LUGAR


-- 4.
DECLARE @COD_PAULO INT
SELECT @COD_PAULO =  NSS 
FROM EMPREGADO
WHERE Nome = 'PAULO' AND Apelido1='MÁXIMO' AND Apelido2='GUERRA'

SELECT @COD_PAULO

BEGIN TRY 

UPDATE EMPREGADO
SET Nome='MÓNICA' , Sexo='M'
WHERE NSS=@COD_PAULO

COMMIT 
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH

-- 5.
SET IMPLICIT_TRANSACTIONS ON
BEGIN TRY

DECLARE @NUMPROYECTO INT
SELECT @NUMPROYECTO = NumProxecto
FROM PROXECTO
WHERE NomeProxecto = 'PORTAL'

UPDATE EMPREGADO_PROXECTO
SET NumProxecto = @NUMPROYECTO
WHERE NSSEmpregado = '9900000'

COMMIT 
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH

