USE CATASTRO;

BEGIN TRANSACTION
BEGIN TRY 


DECLARE @DNI_PRO_1 CHAR(9)

SELECT @DNI_PRO_1 = DNIPROPIETARIO
FROM CASAPARTICULAR
WHERE CALLE='PASIÓN' AND NUMERO=3

INSERT INTO BLOQUEPISOS 
VALUES ('PASIÓN', 3, 3, 'N')

INSERT INTO PISO
VALUES ('PASIÓN', 3, 1, 'A',1, 50, 55, @DNI_PRO_1)

INSERT INTO PISO
VALUES ('PASIÓN', 3, 2, 'A',1, 50, 55, @DNI_PRO_1)

INSERT INTO PISO
VALUES ('PASIÓN', 3, 3, 'A',1, 46, 50, @DNI_PRO_1)

DELETE FROM CASAPARTICULAR
WHERE CALLE='PASIÓN' AND NUMERO=3


COMMIT
END TRY
BEGIN CATCH
	ROLLBACK
	PRINT 'ERROR'
END CATCH


-- 3.
USE EMPRESANEW;

DECLARE @COD_PRO_PORTAL INT 
SELECT @COD_PRO_PORTAL = NumProxecto
FROM PROXECTO
WHERE NomeProxecto='PORTAL'

SELECT * FROM EMPREGADO_PROXECTO
WHERE NumProxecto = @COD_PRO_PORTAL

BEGIN TRANSACTION
BEGIN TRY 

UPDATE EMPREGADO_PROXECTO
SET Horas = HORAS + 15
WHERE Horas IS NULL AND NumProxecto = @COD_PRO_PORTAL

UPDATE EMPREGADO_PROXECTO
SET Horas = 25
WHERE HORAS > 25 AND NumProxecto = @COD_PRO_PORTAL

-- 4.
BEGIN TRANSACTION 
BEGIN TRY 

INSERT INTO PROXECTO
VALUES (@@IDENTITY, 'INFORMATIZACIÓN DE PERMISOS', VIGO, )

SELECT * FROM PROXECTO

COMMIT 
END TRY
BEGIN CATCH 
	ROLLBACK
	PRINT 'AAAAAAAAAAAAAAAAA'
END CATCH 





