USE EMPRESANEW;

--1. 

INSERT INTO HORASEXTRAS
SELECT (GETDATE()-1), NSS, 3
FROM EMPREGADO E
WHERE (E.Nome ='Eligio' AND Apelido1='Rodrigo') OR
			(E.Nome = 'XIAO' AND Apelido1='VECINO' AND Apelido2='VECINO')
			

-- 2.
INSERT INTO CURSO (Nome, Horas) VALUES ('Diseño web', 30)

DECLARE @CODIGOCURSO INT
SELECT @CODIGOCURSO = CODIGO
FROM CURSO
WHERE Nome='Diseño web'

DECLARE @NOMBREPROFESORTECNICO VARCHAR
SELECT @NOMBREPROFESORTECNICO = E.NOME 
FROM DEPARTAMENTO D 
INNER JOIN EMPREGADO E ON D.NSSDirector = E.NSS
WHERE NomeDepartamento = 'TÉCNICO'

INSERT INTO EDICION (Codigo,Numero, Data, Lugar, Profesor)
VALUES (
	@CODIGOCURSO, 1, '15/04/2025', 'PONTEVEDRA', @NOMBREPROFESORTECNICO
)


-- 3.

--(sELECCIONO A TODOS LOS EMPREGADOS MENOS EL JEFE)


--INSERT INTO EDICIONCURSO_EMPREGADO
--VALUES (@CODIGOCURSO, 1, (
--	SELECT NSS
--	FROM EMPREGADO E 
--	INNER JOIN DEPARTAMENTO D ON E.NumDepartamentoPertenece = D.NumDepartamento
--	WHERE NSS != NSSDirector AND D.NomeDepartamento = 'TÉCNICO'
--))

INSERT INTO EDICIONCURSO_EMPREGADO
SELECT @CODIGOCURSO, 1, E.NSS
FROM EMPREGADO E 
INNER JOIN DEPARTAMENTO D ON E.NumDepartamentoPertenece = D.NumDepartamento
WHERE E.NSS != @NOMBREPROFESORTECNICO AND D.NomeDepartamento ='TÉCNICO'

-- 4 
UPDATE EMPREGADOFIXO
SET SALARIO  = Salario + ((Salario*2)/100)
FROM EMPREGADOFIXO EP 
INNER JOIN EMPREGADO E ON E.NSS = EP.NSS
INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NSS
WHERE D.NomeDepartamento ='CONTABILIDAD'

-- 5 

DECLARE @NUMPROYECTO INT
SELECT @NUMPROYECTO = NumProxecto
FROM PROXECTO
WHERE NomeProxecto = 'PORTAL'

UPDATE EMPREGADO_PROXECTO
SET NumProxecto = @NUMPROYECTO
WHERE NSSEmpregado = '9900000'

-- 6

DECLARE @NUMDEPARTAMENTOTECNICO INT
SELECT @NUMDEPARTAMENTOTECNICO = NumDepartamento
FROM DEPARTAMENTO
WHERE NomeDepartamento = 'TÉCNICO'

INSERT INTO PROXECTO (NumProxecto,NomeProxecto, Lugar, NumDepartControla)
VALUES (13,'DESEÑO DE NOVA WEB', 'VIGO', @NUMDEPARTAMENTOTECNICO)

INSERT INTO TAREFA
VALUES (13,1, 'OBJETIVO DE LA PAGINA', DATEADD(DD,15, GETDATE()), DATEADD(DD, 22, GETDATE()), 'MEDIO', NULL)


SELECT * FROM DEPARTAMENTO
EXEC sp_help DEPARTAMENTO
SELECT  * FROM PROXECTO





	
