use CATASTRO


-- 1. SELECT NOMBREZONA, DESCRIPCIÓN, observaciones FROM ZONAURBANA;

-- 2.
--SELECT CALLE, NUMERO, NUMPLANTAS FROM CASAPARTICULAR

-- 3.
--SELECT CALLE, NUMERO, METROSCONSTRUIDOS FROM CASAPARTICULAR WHERE PISCINA ='S'

-- 4.
--SELECT CALLE, NUMERO, METROSSOLAR  FROM VIVIENDA 
--	WHERE TIPOVIVIENDA='UNIFAMILIAR'

--5.
--SELECT * FROM PISO WHERE NUMHABITACIONES = 5;

-- 6.
--SELECT CALLE, NUMERO , METROSSOLAR FROM VIVIENDA 
--	WHERE METROSSOLAR BETWEEN 190 AND 300

--7.
--SELECT * FROM BLOQUEPISOS WHERE NUMPISOS > 15 
--	ORDER BY CALLE, NUMERO

-- 8.
--SELECT CALLE, NUMERO,METROSSOLAR FROM VIVIENDA
--	WHERE NOMBREZONA ='CENTRO'

-- 9.
--SELECT DNI, NOMBRE, APELLIDO1, APELLIDO2 FROM PROPIETARIO 
--	WHERE APELLIDO1 = 'López'
--		ORDER BY APELLIDO1 , APELLIDO2 , NOMBRE

-- 10.
--SELECT CALLE, NUMERO, METROSSOLAR FROM VIVIENDA
--	WHERE (NOMBREZONA = 'CENTRO' OR NOMBREZONA='PALOMAR')
--		AND METROSSOLAR > 450

-- 11.
--SELECT CALLE, NUMERO, ID_HUECO FROM HUECO
	--WHERE TIPO='GARAJE' AND DNIPROPIETARIO=NULL

-- 12.
--SELECT  NOMBREZONA, DESCRIPCIÓN FROM ZONAURBANA
--	WHERE NUMPARQUES>1
--	ORDER BY NUMPARQUES DESC, NOMBREZONA ASC

-- 13.
--SELECT * FROM ZONAURBANA WHERE OBSERVACIONES IS NOT NULL

-- 14.
--SELECT DNI, NOMBRE , APELLIDO1, APELLIDO2 FROM PROPIETARIO
--	WHERE LEN(NOMBRE) > 3
--	ORDER BY NOMBRE, APELLIDO1, APELLIDO2

-- 15. 
--SELECT CALLE, NUMERO, PLANTA, PUERTA, METROSCONSTRUIDOS, METROSUTILES, METROSCONSTRUIDOS - METROSUTILES AS --DIFMETROS FROM PISO	
--	ORDER BY DIFMETROS

-- 16. 
SELECT CALLE, NUMERO, PLANTA, NUMHABITACIONES FROM PISO
	WHERE (NUMHABITACIONES IN 1,3,5,6)

