USE CATASTRO;


-- 63
SELECT CALLE, NUMERO, PLANTA, NUMHABITACIONES, METROSUTILES, NOMBRE ,APELLIDO1
	APELLIDO2
	FROM PISO P
	INNER JOIN PROPIETARIO PR ON P.DNIPROPIETARIO = PR.DNI
	WHERE METROSUTILES > (
		SELECT AVG(METROSUTILES) FROM PISO
)

-- 64
SELECT (
	SELECT AVG(METROSSOLAR) 
	FROM VIVIENDA V
		INNER JOIN BLOQUEPISOS BP ON V.CALLE = BP.CALLE AND V.NUMERO = BP.NUMERO
	WHERE BP.NUMPISOS > 15

) AS [TAMAÓ MEDIO]
	
SELECT METROSSOLAR, NUMPISOS FROM VIVIENDA V 
	INNER JOIN BLOQUEPISOS BP ON V.CALLE = BP.CALLE AND V.NUMERO = BP.NUMERO

-- 65
SELECT DISTINCT (
	SELECT SUM(NUMPARQUES) FROM ZONAURBANA Z
	INNER JOIN VIVIENDA V ON Z.NOMBREZONA = V.NOMBREZONA
) AS [NUM PARQUES]  FROM ZONAURBANA Z 

-- 66
SELECT Z.NOMBREZONA, DESCRIPCIÓN , 
	CAST(CP.CALLE AS VARCHAR(10))  + ', ' + CAST(CP.NUMERO AS VARCHAR(10))
		 + ', ' + CAST(METROSSOLAR AS VARCHAR(10)) + 'm'
FROM ZONAURBANA Z
INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA
INNER JOIN CASAPARTICULAR CP ON CP.NUMERO = V.NUMERO AND CP.CALLE = V.CALLE



-- 67
SELECT DNI , NOMBRE , APELLIDO1 , APELLIDO2 , 
(
	SELECT COUNT(*) FROM PROPIETARIO PR
	INNER JOIN PISO P ON P.DNIPROPIETARIO = PR.DNI
	WHERE PR.DNI = PRO.DNI
	
) [NUM PISOS],
(
	SELECT COUNT(*) FROM CASAPARTICULAR PR 
	INNER JOIN PROPIETARIO P ON P.DNI = PR.DNIPROPIETARIO
	WHERE P.DNI = PRO.DNI
) [NUM CASA]


	FROM PROPIETARIO PRO
	
	
SELECT * FROM CASAPARTICULAR
	WHERE DNIPROPIETARIO = '11111122A'
	
-- 68

SELECT CAST(CP.CALLE AS VARCHAR(10))  + ', ' + CAST(CP.NUMERO AS VARCHAR(10))
		 + ', ' + CAST(Puerta AS VARCHAR(10)), NUMHABITACIONES
FROM PISO CP INNER JOIN PROPIETARIO PRO ON PRO.DNI = CP.DNIPROPIETARIO
WHERE PRO.SEXO = 'M' AND NUMHABITACIONES = (
	SELECT MAX(NUMHABITACIONES) FROM PISO CP
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = CP.DNIPROPIETARIO
	WHERE PRO.SEXO = 'M'
)


SELECT MAX(NUMHABITACIONES) FROM PISO CP
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = CP.DNIPROPIETARIO
	WHERE PRO.SEXO = 'M'
	
--69
SELECT CAST(CP.CALLE AS VARCHAR(10))  + ', ' + CAST(CP.NUMERO AS VARCHAR(10))
		 + ', ' + CAST(METROSCONSTRUIDOS AS VARCHAR(10))  AS [69]
FROM CASAPARTICULAR CP
WHERE METROSCONSTRUIDOS < (
	SELECT AVG(METROSCONSTRUIDOS) FROM CASAPARTICULAR
	WHERE PISCINA = 'N'
) AND PISCINA = 'N'


-- 70

SELECT DNI , NOMBRE , APELLIDO1 , APELLIDO2 , NUMHABITACIONES, 
(
	SELECT COUNT(*) FROM PISO P 
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.DNI = PR.DNI
) NUMPISOS
FROM PROPIETARIO PR INNER JOIN PISO P ON P.DNIPROPIETARIO = PR.DNI
WHERE 
(
	SELECT COUNT(*) FROM PISO P 
	INNER JOIN PROPIETARIO PRO ON PR.DNI = P.DNIPROPIETARIO
	WHERE NUMHABITACIONES > 2 AND
	 PRO.DNI = PR.DNI
) > 1 
 

-- 71
SELECT * FROM PROPIETARIO PRO
	LEFT JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
	WHERE DNIPROPIETARIO IS NULL
 
 -- 72
 SELECT DNI , NOMBRE , APELLIDO1 , APELLIDO2 , 
 (
	SELECT COUNT(*) FROM PISO P
		INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
		WHERE PRO.DNI = PO.DNI
 ) NUMPISOS
 FROM PROPIETARIO PO
 WHERE 
  (
	SELECT COUNT(*) FROM PISO P
		INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
		WHERE PRO.DNI = PO.DNI
 ) > 1 
 AND
 (
	SELECT COUNT(*) FROM CASAPARTICULAR CP 
		INNER JOIN PROPIETARIO PRO ON PRO.DNI = CP.DNIPROPIETARIO
		WHERE PRO.DNI = PO.DNI
 ) <= 0