USE CATASTRO;

SELECT Z.NOMBREZONA, Z.DESCRIPCIÓN
FROM ZONAURBANA Z
INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA
INNER JOIN BLOQUEPISOS BP ON V.CALLE = BP.CALLE AND V.NUMERO = BP.NUMERO
WHERE BP.ASCENSOR='N' 

SELECT DISTINCT  Z.NOMBREZONA, Z.DESCRIPCIÓN,(
	SELECT COUNT(*) 
	FROM BLOQUEPISOS BP
	WHERE BP.CALLE = V.CALLE AND BP.NUMERO = V.NUMERO
	
)
FROM ZONAURBANA Z
INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA