USE CATASTRO

-- 74
	
	
SELECT TOP 1 DNI,COUNT(*) AS CUENTA FROM PROPIETARIO PRO
	INNER JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
	INNER JOIN VIVIENDA V ON P.CALLE = V.CALLE AND P.NUMERO = V.NUMERO
	WHERE V.NOMBREZONA != 'CENTRO' AND NUMHABITACIONES>2
	GROUP BY PRO.DNI
	ORDER BY 2 DESC
	
-- 74
SELECT CAST(BP.CALLE AS VARCHAR(30)) + ', '+ CAST(BP.NUMERO AS VARCHAR) AS BLOQUE,
	MAX(P.METROSUTILES) AS [MAX METROS],
		MAX(P.NUMHABITACIONES) AS [MAX HABITA]
 FROM BLOQUEPISOS BP
	INNER JOIN PISO P ON P.CALLE = BP.CALLE AND BP.NUMERO = P.NUMERO
	GROUP BY BP.CALLE, BP.NUMERO

-- 75
SELECT DNI,NOMBRE, APELLIDO1, 
	ISNULL(V.CALLE + ', ' + CAST(V.NUMERO AS VARCHAR), '') AS [CALLE PROPI]
	FROM PROPIETARIO PRO
	LEFT JOIN CASAPARTICULAR CP ON CP.DNIPROPIETARIO = PRO.DNI
	LEFT JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
	LEFT JOIN VIVIENDA V ON V.CALLE = CP.CALLE AND CP.NUMERO=V.NUMERO
	LEFT JOIN VIVIENDA V2 ON V2.CALLE = P.CALLE AND V2.NUMERO = P.NUMERO
	ORDER BY APELLIDO1 , NOMBRE
	
SELECT NOMBRE, APELLIDO1 , ISNULL(APELLIDO2, '') AS APE2 FROM PROPIETARIO
	INNER JOIN HUECO H ON H.DNIPROPIETARIO = DNI
	WHERE H.TIPO = 'BODEGA' AND
		METROS = (
			SELECT MIN(METROS) FROM HUECO
				WHERE TIPO='BODEGA'
		)
	 