USE CATASTRO

-- 73
	
	
SELECT TOP 1 with ties DNI,COUNT(*) AS CUENTA FROM PROPIETARIO PRO
	INNER JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
	INNER JOIN VIVIENDA V ON P.CALLE = V.CALLE AND P.NUMERO = V.NUMERO
	WHERE V.NOMBREZONA != 'CENTRO' AND NUMHABITACIONES>2
	GROUP BY PRO.DNI
	ORDER BY 2 DESC
	
-- 73 Forma estandar, TABLAS DERIVADAS Y VARIABLES
DECLARE @MAXPISOS INT
SET @MAXPISOS=(

SELECT MAX(NUMPISOS) FROM (
SELECT DNIPROPIETARIO,COUNT(*) AS NUMPISOS
	FROM PISO P
	INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
	WHERE NOMBREZONA <> 'CENTRO' AND NUMHABITACIONES>2
	GROUP BY DNIPROPIETARIO) AS MAXPISOS
	
) 

SELECT NOMBRE , APELLIDO1, DNI , COUNT(*) 
	FROM PISO P 
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
	INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND P.NUMERO = V.NUMERO
	WHERE P.NUMHABITACIONES > 2 AND V.NOMBREZONA<>'CENTRO'
	GROUP BY DNI, NOMBRE, APELLIDO1, APELLIDO2
	HAVING COUNT(*)=@MAXPISOS
	
-- 74
SELECT CAST(BP.CALLE AS VARCHAR(30)) + ', '+ CAST(BP.NUMERO AS VARCHAR) AS BLOQUE,
	MAX(P.METROSUTILES) AS [MAX METROS],
		MAX(P.NUMHABITACIONES) AS [MAX HABITA]
 FROM BLOQUEPISOS BP
	INNER JOIN PISO P ON P.CALLE = BP.CALLE AND BP.NUMERO = P.NUMERO
	GROUP BY BP.CALLE, BP.NUMERO

-- 75
SELECT DISTINCT DNI,NOMBRE, APELLIDO1, 
	ISNULL(V.CALLE + ', ' + CAST(V.NUMERO AS VARCHAR), '') AS [CALLE PROPI]
	FROM PROPIETARIO PRO
	LEFT JOIN CASAPARTICULAR CP ON CP.DNIPROPIETARIO = PRO.DNI
	LEFT JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
	LEFT JOIN VIVIENDA V ON V.CALLE = CP.CALLE AND CP.NUMERO=V.NUMERO OR
		v.calle = P.CALLE AND V.NUMERO = P.NUMERO
	ORDER BY APELLIDO1 , NOMBRE
	
SELECT PRO.DNI, PRO.NOMBRE,
	ISNULL(P.CALLE + ', ' + CAST(P.NUMERO AS VARCHAR), '') AS [CALLE PROPI]
	FROM PROPIETARIO PRO
	INNER JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI
UNION
SELECT PRO.DNI, PRO.NOMBRE,
	ISNULL(P.CALLE + ', ' + CAST(P.NUMERO AS VARCHAR), '') AS [CALLE PROPI]
	FROM PROPIETARIO PRO
	INNER JOIN CASAPARTICULAR P ON P.DNIPROPIETARIO = PRO.DNI
	
	
-- 76
SELECT NOMBRE, APELLIDO1 , ISNULL(APELLIDO2, '') AS APE2 FROM PROPIETARIO
	INNER JOIN HUECO H ON H.DNIPROPIETARIO = DNI
	WHERE H.TIPO = 'BODEGA' AND
		METROS = (
			SELECT MIN(METROS) FROM HUECO
				WHERE TIPO='BODEGA'
		)
		
-- 77 	
	
SELECT NOMBRE, APELLIDO1 , ISNULL(APELLIDO2, ''), DNI 
	FROM PROPIETARIO PRO
	WHERE PRO.SEXO='M'
UNION
SELECT V.CALLE, CAST(V.NUMERO AS VARCHAR(30)), TIPOVIVIENDA, CAST(METROSSOLAR AS VARCHAR) 
	FROM VIVIENDA V 
	INNER JOIN HUECO H ON H.CALLE = V.CALLE AND V.NUMERO = H.NUMERO
	WHERE ((H.TIPO='TRASTERO' AND H.METROS > 10) OR 
		(H.TIPO='GARAJE' AND H.METROS > 13))
		
SELECT DNI, NOMBRE, APELLIDO1 , CALLE, NUMERO , TIPO , METROS
	FROM PROPIETARIO  AS P
		
-- 78
SELECT DISTINCT Z.NOMBREZONA, 
	(
		SELECT COUNT(*) 
		FROM HUECO H
		INNER JOIN VIVIENDA V ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
		WHERE V.NOMBREZONA = Z.NOMBREZONA
	) AS [HUECOS],
	(
		SELECT COUNT(*)
		FROM PISO P 
		INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
		WHERE V.NOMBREZONA = Z.NOMBREZONA
	) AS PISOS,
	(
		SELECT COUNT(*)
		FROM CASAPARTICULAR CP
		INNER JOIN VIVIENDA V ON V.CALLE = CP.CALLE AND V.NUMERO = CP.NUMERO
		WHERE V.NOMBREZONA = Z.NOMBREZONA
	),
	SUM((
		SELECT COUNT(*)
		FROM CASAPARTICULAR CP
		INNER JOIN VIVIENDA V ON V.CALLE = CP.CALLE AND V.NUMERO = CP.NUMERO
		WHERE V.NOMBREZONA = Z.NOMBREZONA
	))
	
	
	FROM ZONAURBANA Z
	INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA
	GROUP BY Z.NOMBREZONA, V.CALLE, V.NUMERO
	
SELECT ZU.NOMBREZONA,COUNT(*) FROM PISO P
	INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
	INNER JOIN ZONAURBANA ZU ON V.NOMBREZONA = ZU.NOMBREZONA
	GROUP BY ZU.NOMBREZONA
	 

	 