USE CATASTRO;

SELECT Z.NOMBREZONA, Z.DESCRIPCIÓN
FROM ZONAURBANA Z
INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA
INNER JOIN BLOQUEPISOS BP ON V.CALLE = BP.CALLE AND V.NUMERO = BP.NUMERO
WHERE BP.ASCENSOR='N' 

SELECT DISTINCT  Z.NOMBREZONA, Z.DESCRIPCIÓN,(
	SELECT COUNT(*) 
	FROM BLOQUEPISOS BP
	WHERE BP.CALLE = V.CALLE AND BP.NUMERO = V.NUMERO
	
)
FROM ZONAURBANA Z
INNER JOIN VIVIENDA V ON V.NOMBREZONA = Z.NOMBREZONA


WITH PROPIETARIOS AS (
SELECT *
FROM PROPIETARIO PRO 
) SELECT * FROM PISO



SELECT DNI , NOMBRE, 
	CASE
		WHEN (
			SELECT COUNT(*) FROM CASAPARTICULAR CP
			WHERE CP.DNIPROPIETARIO = P.DNI
		) > 0 THEN 'POSEE AL MENOS UNA CASA PARTICULAR'
	ELSE 'NO TIENE NINGUNA CASA PARTICULAR'
	END
FROM PROPIETARIO P 
WHERE P.SEXO = 'H'