USE EMPRESANEW;
--1.
--SELECT E.NOME, E.Localidade FROM EMPREGADO E 
--	WHERE Localidade IN ('PONTEVEDRA', 'SANTIAGO', 'VIGO')

-- 2.
SELECT F.NOME , F.DataNacemento FROM FAMILIAR F
	INNER JOIN EMPREGADO E ON E.NSS = F.NSS_empregado
	
	WHERE F.Parentesco IN ('HIJO', 'HIJA')
	ORDER BY F.Parentesco DESC, F.DataNacemento ASC
	
	
	
SELECT DISTINCT E.LOCALIDADE, 
	CASE E.LOCALIDADE
		WHEN 'LUGO' THEN 'LUCENSE'
	ELSE 'OTRO/A'
		
	END AS GENTILICIOS
FROM EMPREGADO E
 
 
 SELECT	COUNT(E.CP) AS CONTEO
	FROM EMPREGADO E
	GROUP BY E.NOME
	
SELECT D.NomeDepartamento,
		COUNT(NSS) AS [NUMERO DE EMPLEADOS] 
	FROM EMPREGADO E
	INNER JOIN DEPARTAMENTO D 
		ON E.NumDepartamentoPertenece = D.NumDepartamento
	WHERE D.NomeDepartamento LIKE '[A-Z]%'
	GROUP BY NumDepartamentoPertenece, D.NomeDepartamento
	
	HAVING COUNT(NSS) > 5
	ORDER BY 2 ASC

	
SELECT CP FROM EMPREGADO