USE EMPRESANEW;

SELECT NomeDepartamento,COUNT(*) NUM_EMPLEADOS
FROM EMPREGADO E 
INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NumDepartamentoPertenece
WHERE (
	SELECT COUNT(*) FROM DEPARTAMENTO D2
	INNER JOIN PROXECTO P ON P.NumDepartControla = D.NumDepartamento
) > 2
GROUP BY NomeDepartamento

-- 2A 

DECLARE @MEDIA FLOAT

SET @MEDIA =  (SELECT CEILING(COUNT(*)/(SELECT COUNT(*) FROM DEPARTAMENTO)) AS MEDIA
FROM EMPREGADO E)

SELECT NomeDepartamento, (
	SELECT COUNT(*) FROM DEPARTAMENTO D2 
	INNER JOIN PROXECTO P2 ON P2.NumDepartControla = D.NumDepartamento
) AS NUM_PROYE
FROM DEPARTAMENTO D
WHERE (
	SELECT COUNT(*) FROM EMPREGADO E3
	INNER JOIN DEPARTAMENTO D3 ON E3.NumDepartamentoPertenece = D.NumDepartamento
) > @MEDIA

-- 3A
SELECT DISTINCT NomeDepartamento, (
	SELECT COUNT(*) FROM PROXECTO P3
	WHERE P3.NumDepartControla = D.NumDepartamento
) AS [NUM PRO CONTROLAN]
FROM DEPARTAMENTO D
INNER JOIN PROXECTO P ON P.NumDepartControla = D.NumDepartamento
WHERE (
	SELECT COUNT(*) FROM EMPREGADO E2
	WHERE (
		SELECT COUNT(*) FROM FAMILIAR F2
		WHERE F2.NSS_empregado = E2.NSS
	) < 3
	
) > 1

	SELECT NomeDepartamento,COUNT(*) AS B
	FROM EMPREGADO E
	INNER JOIN FAMILIAR F ON F.NSS_empregado = E.NSS
	INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NumDepartamentoPertenece
	GROUP BY D.NomeDepartamento
	
	
		SELECT COUNT(*) AS B
	FROM EMPREGADO E
	INNER JOIN FAMILIAR F ON F.NSS_empregado = E.NSS
	GROUP BY E.NSS
	HAVING COUNT(*) < 3


-- BIEN
SELECT COUNT(*) AS [EMPLEADOS] 
FROM (
	SELECT COUNT(*) AS B
	FROM EMPREGADO E
	INNER JOIN FAMILIAR F ON F.NSS_empregado = E.NSS
	GROUP BY E.NSS
	HAVING COUNT(*) < 3
) AS SUB



SELECT COUNT(*) AS [EMPLEADOS] 
FROM (
	SELECT COUNT(*) AS B
	FROM EMPREGADO E
	INNER JOIN FAMILIAR F ON F.NSS_empregado = E.NSS
	GROUP BY E.NSS
	HAVING COUNT(*) < 3
) AS SUB
GROUP BY 

SELECT D.NomeDepartamento, COUNT(*) AS NUM_PROYE
FROM DEPARTAMENTO D
INNER JOIN PROXECTO P ON D.NumDepartamento = P.NumDepartControla
WHERE  (
	SELECT COUNT(*) FROM FAMILIAR F
	INNER JOIN EMPREGADO E ON E.NSS = F.NSS_empregado
	WHERE E.NumDepartamentoPertenece = D.NumDepartamento
	HAVING COUNT(*) < 3 
) > 1
GROUP BY D.NomeDepartamento



