-- 38 
SELECT E.NSS,LOWER(LEFT(E.NOME, 2)+ SUBSTRING(E.Apelido1, 2,4)+
	LEFT(E.Localidade,1) +RIGHT(E.Localidade,1)),D.NomeDepartamento
FROM EMPREGADO E 
INNER JOIN DEPARTAMENTO D ON D.NumDepartamento = E.NumDepartamentoPertenece

-- 40 
SELECT E.Localidade,E.NSS
FROM EMPREGADO E 
INNER JOIN EMPREGADO_PROXECTO EP ON EP.NSSEmpregado = E.NSS
INNER JOIN PROXECTO P ON 
WHERE 
GROUP BY  E.Localidade, E.NSS

SELECT  NomeProxecto, NSS , Nome, Apelido1
FROM EMPREGADO E 
INNER JOIN PROXECTO P ON E.Localidade = P.Lugar
WHERE Localidade NOT IN (
	SELECT LUGAR FROM PROXECTO P
	INNER JOIN EMPREGADO_PROXECTO EP ON EP.NumProxecto = P.NumProxecto
	WHERE EP.NSSEmpregado = E.NSS
)

-- 41 
SELECT  NomeProxecto, NSS , Nome, Apelido1
FROM EMPREGADO E 
INNER JOIN PROXECTO P ON E.Localidade = P.Lugar
WHERE Localidade NOT IN (
	SELECT LUGAR FROM PROXECTO P
	INNER JOIN EMPREGADO_PROXECTO EP ON EP.NumProxecto = P.NumProxecto
	WHERE EP.NSSEmpregado = E.NSS )
	AND
	(
		SELECT (40-SUM(HORAS))  AS HORAs_LIBRES
		FROM EMPREGADO_PROXECTO EP WHERE NSSEmpregado = E.NSS
	) > 10
