USE EMPRESANEW;

-- 17.

SELECT SUM(SALARIO) AS [SUMA SALARIO], AVG(SALARIO) [MEDIA SALARIOS] FROM EMPREGADOFIXO

-- 18.
SELECT  NomeDepartamento, 
		COUNT(*) AS [NUMERO EMPREGADOS FIXOS], 
		AVG(SALARIO) AS [MEDIA SALARIOS]  
		FROM EMPREGADOFIXO EF
		INNER JOIN EMPREGADO E ON EF.NSS = E.NSS
		INNER JOIN DEPARTAMENTO ON NumDepartamentoPertenece =					NumDepartamento
		GROUP BY NomeDepartamento
		
-- 19
SELECT	YEAR(DATANACEMENTO) AS AÑO, 
		COUNT(*) AS [NUMERO DE NACIDOS] FROM EMPREGADO
	WHERE YEAR(DataNacemento) > 1969
	GROUP BY YEAR(DATANACEMENTO)
		
-- 20
SELECT	'EL NUMERO DE HOMBRES ES ' +  CAST((SELECT COUNT(*) FROM EMPREGADO WHERE Sexo='H') AS VARCHAR(3)) AS HOMBRES ,
		'EL NUMERO DE MUJERES ES ' +CAST((SELECT COUNT(*) FROM EMPREGADO WHERE Sexo='M') AS VARCHAR(3)) AS MUJERES
	
-- 21 	
SELECT 
	(SELECT COUNT(EF.NSS)FROM EMPREGADO E
		INNER JOIN EMPREGADOFIXO EF ON E.NSS = EF.NSS
		WHERE Sexo='M') 
		
		AS [EMPLEADOS FIXOS MUJERES] ,
		
	(SELECT COUNT(EF.NSS)FROM EMPREGADO E
		INNER JOIN EMPREGADOFIXO EF ON E.NSS = EF.NSS
		WHERE Sexo='H') 
		
		AS [EMPLEADOS FIXOS HOMBRES]
		
		-- FALTAN LOS TEMPORALES

-- 22
SELECT (E.NOME + ' ' + E.APELIDO1 + ' ' + E.APELIDO2) AS [NOMBRE COMPLETO], Parentesco, COUNT(F.NSS)
	FROM EMPREGADO E
	INNER JOIN FAMILIAR F ON E.NSS = NSS_empregado
	GROUP BY F.Parentesco, E.NOME, E.Apelido1, E.Apelido2
	HAVING COUNT(*) > 1
-- MAL 

SELECT Nome + Apelido1, SUM(EP.HORAS) AS [NUM HORAS] 
	FROM EMPREGADO E
	INNER JOIN EMPREGADO_PROXECTO EP ON E.NSS = ep.NSSEmpregado
	GROUP BY E.NOME, E.Apelido1
	
	
	
	
