USE EMPRESANEW;

-- 17.

SELECT SUM(SALARIO) AS [SUMA SALARIO], AVG(SALARIO) [MEDIA SALARIOS] FROM EMPREGADOFIXO

-- 18.
SELECT  NomeDepartamento, 
		COUNT(*) AS [NUMERO EMPREGADOS FIXOS], 
		AVG(SALARIO) AS [MEDIA SALARIOS]  
		FROM EMPREGADOFIXO EF
		INNER JOIN EMPREGADO E ON EF.NSS = E.NSS
		INNER JOIN DEPARTAMENTO ON NumDepartamentoPertenece =					NumDepartamento
		GROUP BY NomeDepartamento
		
-- 19
SELECT	YEAR(DATANACEMENTO) AS AÑO, 
		COUNT(*) AS [NUMERO DE NACIDOS] FROM EMPREGADO
	WHERE YEAR(DataNacemento) > 1969
	GROUP BY YEAR(DATANACEMENTO)
		
-- 20
SELECT	'EL NUMERO DE HOMBRES ES ' +  CAST((SELECT COUNT(*) FROM EMPREGADO WHERE Sexo='H') AS VARCHAR(3)) AS HOMBRES ,
		'EL NUMERO DE MUJERES ES ' +CAST((SELECT COUNT(*) FROM EMPREGADO WHERE Sexo='M') AS VARCHAR(3)) AS MUJERES
	
-- 21 	