USE CATASTRO;

-- 1.
SELECT CALLE, NUMERO , PLANTA, PUERTA, NUMHABITACIONES, DNIPROPIETARIO,
	CASE
		WHEN NUMHABITACIONES BETWEEN 0 AND 2 
			THEN 'Ideal Parejas sin o con 1 hijo'
		WHEN NUMHABITACIONES =3
			THEN 'Ideal Parejas con dos hijos'	
		WHEN NUMHABITACIONES > 3
			THEN 'Ideal Parejas con más de dos hijos'	
		ELSE ''
	END
	FROM PISO
	WHERE DNIPROPIETARIO LIKE '%[ABH]'
-- 2.
SELECT * FROM PROPIETARIO 
	WHERE (TELEFONO LIKE '[610]%') OR (TELEFONO LIKE '[565]%')
	ORDER BY LEN(NOMBRE) ASC , NOMBRE DESC 

--3. 
SELECT *  FROM PROPIETARIO 
	WHERE (TELEFONO LIKE '[610]%') OR (TELEFONO LIKE '[565]%')
	GROUP BY DNI, NOMBRE
	ORDER BY LEN(NOMBRE) ASC , NOMBRE DESC 
	
-- 4.
SELECT * FROM VIVIENDA 
	WHERE CHARINDEX(' ', CALLE) = 0
	ORDER BY 
	CASE TIPOVIVIENDA WHEN 'BLOQUE' THEN METROSSOLAR END DESC,
	CASE TIPOVIVIENDA WHEN 'CASA' THEN LEN(NOMBREZONA) END ASC

-- 5.
SELECT TOP 1 * FROM ZONAURBANA
	ORDER BY NUMPARQUES DESC

SELECT * FROM ZONAURBANA
	WHERE NUMPARQUES = (SELECT MAX(NUMPARQUES) FROM ZONAURBANA)
	
	


	
	
