USE EMPRESANEW;

-- 2.
SELECT TOP 1 WITH TIES YEAR(DataNacemento) AS AÑO , COUNT(*) AS EMPREGADOS

FROM EMPREGADO
GROUP BY YEAR(DataNacemento)
ORDER BY 2 DESC 

-- 2.
SELECT YEAR(DataNacemento) AS AÑO , COUNT(*) AS EMPREGADOS

FROM EMPREGADO
GROUP BY YEAR(DataNacemento)
HAVING  COUNT(*) >= all (SELECT COUNT(*) FROM EMPREGADO 
						GROUP BY YEAR(DataNacemento))

