USE CATASTRO;

-- 42 
SELECT  MAX(H.PLANTA) AS [NUM MAX PLANTA] FROM PROPIETARIO P
	INNER JOIN PISO H ON H.DNIPROPIETARIO = P.DNI
	WHERE P.NOMBRE LIKE'M%'
	
-- 43 
SELECT SUM(NUMPARQUES) AS [TOTAL PARQUES] FROM ZONAURBANA

-- 44 
	

	
	