USE CATASTRO;

SELECT NOMBREZONA , ISNULL(OBSERVACIONES, 'NO HAY OBSERVACIONES')
FROM ZONAURBANA
GROUP  BY NOMBREZONA, OBSERVACIONES

-- 80

SELECT RIGHT(V.NOMBREZONA, 2), DNI , NOMBRE, APELLIDO1
FROM PROPIETARIO PRO
INNER JOIN CASAPARTICULAR CP ON CP.DNIPROPIETARIO = PRO.DNI
INNER JOIN VIVIENDA V ON CP.CALLE = V.CALLE AND CP.NUMERO = V.NUMERO
ORDER BY RIGHT(NOMBREZONA, 2), V.CALLE

-- 81
SELECT TOP 1 DNI,NOMBRE,APELLIDO1 
FROM PROPIETARIO
ORDER BY NEWID()

-- 82
SELECT P.CALLE, P.NUMERO, P.PLANTA, P.PUERTA, NUMHABITACIONES, 
	METROSUTILES, PRO.NOMBRE, PRO.APELLIDO1,
	
	CASE NUMHABITACIONES
		WHEN 1 THEN 'APARTAMENTO'
		WHEN 2 THEN 'APARTAMENTO'
		WHEN 3 THEN 'PISO'
		WHEN 4 THEN 'PISO'
		ELSE 'PISAZO'
	END AS [TIPO PISO]
	
	FROM PISO P 
	INNER JOIN PROPIETARIO PRO ON PRO.DNI = P.DNIPROPIETARIO
	INNER JOIN VIVIENDA V ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
	WHERE (
		SELECT NUMPARQUES FROM ZONAURBANA ZU
		WHERE ZU.NOMBREZONA = V.NOMBREZONA
	) > 1 
	AND 
	(
		SELECT COUNT(*) FROM CASAPARTICULAR CP1
		INNER JOIN VIVIENDA V1 ON CP1.CALLE = V1.CALLE AND V1.NUMERO = CP1.NUMERO
		WHERE V1.NOMBREZONA = V.NOMBREZONA
	) > 0

-- 83
SELECT NOMBRE+' '+APELLIDO1+' POSEE UN ' + TIPOVIVIENDA + ' EN AL CALLE ' 
		+ V.CALLE + 'Nº' + CAST(V.NUMERO AS VARCHAR)
FROM VIVIENDA V
LEFT JOIN CASAPARTICULAR CP ON V.CALLE = CP.CALLE AND V.NUMERO = CP.NUMERO
LEFT JOIN PISO P ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
INNER JOIN PROPIETARIO PRO ON PRO.DNI = CP.DNIPROPIETARIO
	 OR PRO.DNI = P.DNIPROPIETARIO
	 
	 
	 
SELECT NOMBRE+' '+APELLIDO1+' POSEE UN ' + 'PISO' + ' EN AL CALLE ' 
		+ P.CALLE + 'Nº' + CAST(P.NUMERO AS VARCHAR) 
FROM PISO P 
INNER JOIN PROPIETARIO PRO ON P.DNIPROPIETARIO = PRO.DNI
UNION ALL
SELECT NOMBRE+' '+APELLIDO1+' POSEE UN ' + 'CASA' + ' EN AL CALLE ' 
		+ P.CALLE + 'Nº' + CAST(P.NUMERO AS VARCHAR) 
FROM CASAPARTICULAR P 
INNER JOIN PROPIETARIO PRO ON P.DNIPROPIETARIO = PRO.DNI



-- 84
SELECT * FROM (
SELECT P.CALLE, P.NUMERO, P.PLANTA, P.PUERTA, 
	P.NUMHABITACIONES, P.METROSUTILES AS METROS, NULL AS PISCINA , 'PISO' AS TIPO
FROM PISO P
UNION ALL 
SELECT CP.CALLE, CP.NUMERO, NULL AS PLANTA, NULL AS PUERTA,
	NULL AS NUMHABITACIONES, V.METROSSOLAR AS METROS, CP.PISCINA,  'CASA' AS TIPO
FROM CASAPARTICULAR CP
INNER JOIN VIVIENDA V ON CP.CALLE = V.CALLE AND CP.NUMERO = V.NUMERO
) AS RESULTADO 
ORDER BY CASE 
	WHEN TIPO = 'PISO' THEN NUMHABITACIONES
	WHEN TIPO = 'CASA' THEN METROS 
	END

	
-- 85

SELECT (
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'H'
),(
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'M'
)

SELECT CASE
	WHEN (
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'H'
	) > (
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'M'
	) THEN 'LOS HOMBRES TIENEN MAS PISOS'

WHEN (
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'M'
	) = (
	SELECT COUNT(*) FROM PROPIETARIO PRO
	INNER JOIN PISO P ON PRO.DNI = P.DNIPROPIETARIO
	WHERE PRO.SEXO = 'H'
	) THEN 'TIENEN LOS MISMOS PISOS HOMBRES Y MUJERES'
ELSE 'LAS MUJERES MÁS'
END AS '85. Quien posee más pisos: los hombres o las mujeres?'

-- 86


SELECT NOMBRE, APELLIDO1,  'PISO' AS [TIPO PROPIEDAD],  
(
	SELECT CAST(COUNT(*) AS VARCHAR(2))
	FROM PISO P 
	WHERE P.DNIPROPIETARIO = PRO.DNI
), 'VIVIENDA UNIFAMILIAR' AS [TIPO PROPÌEDAD], 
(
	SELECT CAST(COUNT(*) AS VARCHAR(2))
	FROM CASAPARTICULAR P 
	WHERE P.DNIPROPIETARIO = PRO.DNI
), 'GARAJE' AS [TIPO PROPÌEDAD], 
(
	SELECT CAST(COUNT(*) AS VARCHAR(2))
	FROM HUECO P 
	WHERE P.DNIPROPIETARIO = PRO.DNI AND TIPO='GARAJE'
), 'TRASTERO' AS [TIPO PROPÌEDAD], 
(
	SELECT CAST(COUNT(*) AS VARCHAR(2))
	FROM HUECO P 
	WHERE P.DNIPROPIETARIO = PRO.DNI AND P.TIPO='TRASTERO'
)



FROM PROPIETARIO PRO 


SELECT NOMBRE , APELLIDO1 , 'PISO' AS [TIPO PROPIEDAD], COUNT(*) AS NUMERO
FROM PROPIETARIO
INNER JOIN PISO P ON P.DNIPROPIETARIO = DNI
GROUP BY NOMBRE, APELLIDO1

UNION ALL 

SELECT NOMBRE , APELLIDO1 , 'VIVIENDA UNIFAMILIAR', COUNT(*)
FROM PROPIETARIO
INNER JOIN CASAPARTICULAR P ON P.DNIPROPIETARIO = DNI
GROUP BY NOMBRE,APELLIDO1

UNION ALL

SELECT NOMBRE , APELLIDO1 , 'GARAJE', COUNT(*)
FROM PROPIETARIO
INNER JOIN HUECO P ON P.DNIPROPIETARIO = DNI
WHERE P.TIPO = 'GARAJE'
GROUP BY NOMBRE,APELLIDO1

UNION ALL

SELECT NOMBRE , APELLIDO1 , 'TRASTERO', COUNT(*)
FROM PROPIETARIO
INNER JOIN HUECO P ON P.DNIPROPIETARIO = DNI
WHERE P.TIPO = 'TRASTERO'
GROUP BY NOMBRE,APELLIDO1

ORDER BY NOMBRE
	

SELECT NOMBRE, APELLIDO1
FROM PROPIETARIO PRO 
INNER JOIN PISO P ON P.DNIPROPIETARIO = PRO.DNI