USE CATASTRO;

--IF EXISTS SYS.TABLES WHERE NAME = 'VIVIENDA'
--	DROP TABLE VIVIENDA; 

INSERT INTO VIVIENDA (CALLE, NUMERO, TIPOVIVIENDA, CODIGOPOSTAL, NOMBREZONA)
	VALUES ('Ponzano', 44, 'Casa', 36940, 'Centro')
	
DECLARE @DNIPROPIETARIO CHAR(9)
SELECT @DNIPROPIETARIO = DNI 
		FROM PROPIETARIO
		WHERE NOMBRE = 'MALENA' AND APELLIDO1 = 'Franco' AND APELLIDO2='Valiño'
	
	
	
INSERT INTO CASAPARTICULAR (CALLE, NUMERO , NUMPLANTAS, DNIPROPIETARIO)
	VALUES ('Ponzano' , 44 , 2 , @DNIPROPIETARIO)
	
UPDATE CASAPARTICULAR SET METROSCONSTRUIDOS = METROSCONSTRUIDOS+20,
						PISCINA = 'S'
		WHERE CALLE = 'Damasco' AND NUMERO = 6
					
UPDATE HUECO 
SET OBSERVACIONES = ISNULL(OBSERVACIONES, '') + 'SE INSTALO UN ENCHUFE'
WHERE CALLE ='ZURBARÁN' AND NUMERO = 101 AND TIPO = 'BODEGA'

SELECT COUNT(*) AS TOTAL
FROM PISO
WHERE DNIPROPIETARIO NOT IN (
	SELECT DNIPROPIETARIO 
	FROM CASAPARTICULAR
)

-- CORREGIDO

SELECT NOMBRE , APELLIDO1 , APELLIDO2 
FROM PROPIETARIO PRO
WHERE DNI IN (
	SELECT DNI
	FROM HUECO H
	INNER JOIN VIVIENDA V
		ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
	WHERE (TIPO = 'GARAJE' OR TIPO='TRASTERO')
	
		AND NOMBREZONA IN ('PALOMAR', 'CENTRO')
		
		AND DNI NOT IN 
		(
			SELECT DNIPROPIETARIO FROM PISO
		)
		
		AND DNI NOT IN 
		(
			SELECT DNIPROPIETARIO FROM CASAPARTICULAR
		)	
		
)


-- MAL 
SELECT NOMBRE , APELLIDO1 , APELLIDO2 
FROM PROPIETARIO PRO
WHERE DNI IN (
	SELECT DNI
	FROM HUECO H
	INNER JOIN VIVIENDA V
		ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
	WHERE (TIPO = 'GARAJE' OR TIPO='TRASTERO')
	
		AND NOMBREZONA IN ('PALOMAR', 'CENTRO')
	
		AND ((
			SELECT NOMBREZONA 
			FROM VIVIENDA 
			WHERE H.CALLE = CALLE AND H.NUMERO =					NUMERO
		) = 'PALOMAR' OR 
		(
			SELECT NOMBREZONA 
			FROM VIVIENDA 
			WHERE H.CALLE = CALLE AND H.NUMERO =					NUMERO
		) = 'CENTRO')
		
		AND DNI NOT IN 
		(
			SELECT DNIPROPIETARIO FROM PISO
		)
		
		AND DNI NOT IN 
		(
			SELECT DNIPROPIETARIO FROM CASAPARTICULAR
		)	
		
)

-- pEPA
SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM PROPIETARIO
WHERE DNI IN (
	SELECT DISTINCT DNIPROPIETARIO
	FROM HUECO H INNER JOIN VIVIENDA V 
		ON H.CALLE = V.CALLE AND H.NUMERO = V.NUMERO
		WHERE TIPO IN ('GARAJE', 'TRASTERO') AND
		NOMBREZONA IN ('PALOMAR', 'CENTRO')
	) AND DNI NOT IN (SELECT DNIPROPIETARIO FROM PISO)
		AND DNI NOT IN (SELECT DNIPROPIETARIO FROM CASAPARTICULAR)


	

