USE MASTER;

IF EXISTS (SELECT * FROM SYS.databases WHERE name='Universidad')
	DROP DATABASE Universidad;
	
CREATE DATABASE Universidad
ON PRIMARY 
(
	NAME='ARCHIVOPRINCIPAL',
	FILENAME='C:\basedatos\Universidad\ARCHIVOPRINCIPAL.MDF',
	SIZE=3MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=3%
)
LOG ON 
(
	NAME=ARCHIVOLOGS,
	FILENAME='C:\basedatos\Universidad\LOGS1.LDF',
	SIZE=20MB,
	MAXSIZE=20MB,
	FILEGROWTH=0
);
GO
USE UNIVERSIDAD;


GO
CREATE SCHEMA UNIVERSIDAD;

GO
ALTER DATABASE UNIVERSIDAD
	ADD FILEGROUP GROUP_UNIVERSIDAD;


GO
ALTER DATABASE UNIVERSIDAD
	ADD FILE(
		NAME='ARCHIVO_UNIVERSIDAD1',
		FILENAME='C:\basedatos\Universidad\ARCHIVO_UNIVERSIDAD1.NDF'
) TO FILEGROUP GROUP_UNIVERSIDAD

GO

CREATE TYPE MAYOR_EDAD
	FROM BIT;
CREATE TYPE FECHA
	FROM DATE;
	
GO
CREATE TABLE UNIVERSIDAD.ESTUDIANTES(
	ID_ESTUDIANTES SMALLINT IDENTITY(100,1),
	NOMBRE	VARCHAR(50) NOT NULL,
	APELLIDO	VARCHAR(50),
	FECHA_NACIMIENTO	FECHA NOT NULL,
	EMAIL	VARCHAR(100)NOT NULL,
	TELEFONO	VARCHAR(15) NOT NULL,
	
	CONSTRAINT ID_ESTUDIANTES PRIMARY KEY (ID_ESTUDIANTES),
	CONSTRAINT _U_TELEFONO UNIQUE (TELEFONO),
	
/*
	CONSTRAINT CH_EDAD	CHECK(
		(FECHA_NACIMIENTO >= DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE())
			AND (MONTH(GETDATE()) > MONTH(FECHA_NACIMIENTO)
			OR MONTH (GETDATE()) = MONTH(FECHA_NACIMIENTO) 
				AND DAY(GETDATE()) >= DAY(FECHA_NACIMIENTO)))),
*/				
	
	
) ON GROUP_UNIVERSIDAD


GO
INSERT INTO UNIVERSIDAD.ESTUDIANTES(NOMBRE, APELLIDO, 
			FECHA_NACIMIENTO,EMAIL,TELEFONO)VALUES
		('Yago', 'Otero', '11-02-2003', 'yagootero2003@gmail.com', '692433876')

--SELECT * FROM UNIVERSIDAD.ESTUDIANTES;
--EXEC sp_helpdb UNIVERSIDAD;
--EXEC sp_help 'UNIVERSIDAD.ESTUDIANTES';


GO
ALTER DATABASE UNIVERSIDAD
	ADD LOG FILE (
		NAME='LOGS_UNIVERSIDAD2',
		FILENAME='C:\basedatos\Universidad\LOGS_UNIVERSIDAD2.LDF'
) 

--EXEC sp_helpdb UNIVERSIDAD;


GO
CREATE TABLE CURSOS(
	ID_CURSO	SMALLINT IDENTITY,
	NOMBRE	VARCHAR NOT NULL,
	DESCRIPCION	TEXT NULL,
	CREDITOS SMALLINT NOT NULL,
	
	CONSTRAINT PK_CURSOS PRIMARY KEY (ID_CURSO) 
	
)

CREATE TABLE PROFESORES(
	ID SMALLINT IDENTITY,
	NOMBRE	VARCHAR NOT NULL,
	APELLIDO	VARCHAR NOT NULL,
	ESPECIALIDAD	VARCHAR,
	
	CONSTRAINT PK_PROFESORES PRIMARY KEY (ID),
	CONSTRAINT CK_ESPECIALIDAD CHECK(
		(ESPECIALIDAD IN ('INFORMATICA', 'PSICOLOGIA'))
	)
)


CREATE TABLE DEPARTAMENTOS(
	ID	SMALLINT IDENTITY,
	NOMBRE	VARCHAR NOT NULL,
	
	CONSTRAINT PK_DEPAR PRIMARY KEY (ID)
)

CREATE TABLE ASIGNACIONES(
	ID_ASIGNACION	SMALLINT IDENTITY,
	ID_PROFESOR		SMALLINT,
	ID_CURSO		SMALLINT,
	FECHA_ASIGNACION FECHA NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	
	CONSTRAINT PK_ASIGNACIONES PRIMARY KEY (ID_ASIGNACION) ,
	
	CONSTRAINT FK_PROFESOR_ASIGNACIONES FOREIGN KEY (ID_PROFESOR)
		REFERENCES PROFESORES
)

GO
CREATE SCHEMA PROFESORES;

GO
ALTER SCHEMA PROFESORES TRANSFER DBO.ASIGNACIONES;

--EXEC sp_help 'PROFESORES.ASIGNACIONES'
GO
ALTER TABLE PROFESORES.ASIGNACIONES
	ADD CONSTRAINT FK_CURSO_ASIGNACIONES FOREIGN KEY (ID_CURSO)
		REFERENCES CURSOS
		
GO
CREATE TABLE MATRICULAS(
	ID_MATRICULA	SMALLINT IDENTITY,
	ID_ESTUDIANTE	SMALLINT,
	ID_CURSO		SMALLINT,
	FECHA_MATRICULA	FECHA NOT NULL,
	
	CONSTRAINT PK_MAYTRICULAS PRIMARY KEY (ID_MATRICULA),
	
	CONSTRAINT FK_MATRICULAS_ESTUDIANTES FOREIGN KEY (ID_ESTUDIANTE)
		REFERENCES UNIVERSIDAD.ESTUDIANTES ON UPDATE CASCADE ON DELETE CASCADE,
		
	CONSTRAINT FK_MATRICULAS_CURSO FOREIGN KEY (ID_CURSO) 
		REFERENCES CURSOS
	
)

GO
ALTER SCHEMA PROFESORES TRANSFER DBO.MATRICULAS;


GO
ALTER TABLE PROFESORES.MATRICULAS
	ALTER COLUMN FECHA_MATRICULA DATE NOT NULL;


GO
IF EXISTS (SELECT * FROM SYS.tables WHERE name='MATRICULAS' 
			AND SCHEMA_ID = SCHEMA_ID('PROFESORES'))
BEGIN
	DROP TABLE PROFESORES.MATRICULAS
	PRINT 'TABLA BORRADA'
END
ELSE 
	PRINT 'NO SE ENCONTRO LA TABLA'
	
	
CREATE TABLE TEST(
	FECHA_NACIMIENTO	DATE NOT NULL,
	EDAD	INT DEFAULT DATEDIFF(YY, '11-02-2003', GETDATE()),
	CHAMPIONS	AS DATEADD(DD, -17,GETDATE()),
	IVA	AS 100*0.21 + 100
	
/*	
	CONSTRAINT CH_EDAD	CHECK(
		(FECHA_NACIMIENTO >= DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE())
			AND (MONTH(GETDATE()) > MONTH(FECHA_NACIMIENTO)
			OR MONTH (GETDATE()) = MONTH(FECHA_NACIMIENTO) 
				AND DAY(GETDATE()) >= DAY(FECHA_NACIMIENTO)))),

	
)
*/
)

GO
INSERT INTO TEST (FECHA_NACIMIENTO) VALUES ('11-02-2003')
SELECT * FROM TEST




