IF DB_ID ('BD_AlterDB1') IS NOT NULL
BEGIN
	DROP DATABASE BD_ALTERDB1;
END

GO
CREATE DATABASE BD_ALTERDB1;

GO
ALTER DATABASE BD_ALTERDB1
ADD FILE
( NAME='ArchivoAnadido',
	FILENAME='C:\basedatos\BD_ALTERDB1\ARCHIVOANADIDO1.ndf',
	SIZE=3MB,
	FILEGROWTH=2MB
);

GO
ALTER DATABASE BD_ALTERDB1
MODIFY FILE
( NAME='BD_ALTERDB1',
	SIZE=5MB
);

GO
--ALTER DATABASE BD_ALTERDB1
--MODIFY FILE
--( NAME='BD_ALTERDB1',
--	SIZE=3MB
--);


GO

IF DB_ID ('BD_AlterDB2') IS NOT NULL
	DROP DATABASE BD_AlterDB2;

GO

CREATE DATABASE BD_AlterDB2
ON PRIMARY
(	NAME='BD_AlterDB2_DATA',
	FILENAME='C:\basedatos\BD_AlterDB2\BD_AlterDB2_DATA.MDF' ,
	SIZE=3MB,
	MAXSIZE=4MB,
	FILEGROWTH=0MB

);

GO
ALTER DATABASE BD_AlterDB2
MODIFY FILE
( NAME='BD_AlterDB2_DATA',
	MAXSIZE=6MB
	
);
exec sp_helpdb 'BD_AlterDB2';


GO
IF DB_ID ('BD_AlterDB3') IS NOT NULL
BEGIN
	DROP DATABASE BD_AlterDB3;
END

GO
CREATE DATABASE BD_AlterDB3
ON PRIMARY
(	name ='C:\basedatos\BD_AlterDB3',
	FILENAME='C:\basedatos\BD_AlterDB3\BD_AlterDB3.MDF',
	SIZE=3MB,
	MAXSIZE=15MB,
	FILEGROWTH=1MB
);

GO
IF DB_ID('BD_AlterDB3') IS NOT NULL
BEGIN
	DROP DATABASE BD_AlterDB3
END
GO

CREATE DATABASE BD_AlterDB3
ON PRIMARY
(	NAME='BD_AlterDB3_DATA1',
	FILENAME='C:\basedatos\BD_AlterDB3\BD_AlterDB3_DATA1.MDF',
	SIZE=3MB,
	MAXSIZE=10MB,
	FILEGROWTH=1MB

);

GO 
ALTER DATABASE BD_AlterDB3
ADD FILE
(	NAME='BD_AlterDB3_DATA2',
	FILENAME='C:\basedatos\BD_AlterDB3\BD_AlterDB3_DATA2.NDF',
	SIZE=5MB,
	MAXSIZE=15MB,
	FILEGROWTH=2MB

);

GO
ALTER DATABASE BD_AlterDB3
ADD FILEGROUP GRUPO1;


GO
ALTER DATABASE BD_AlterDB3
ADD FILE 
(	NAME='BD_AlterDB3_DATA3',
	FILENAME='C:\basedatos\BD_AlterDB3\BD_AlterDB3_DATA3.NDF',
	SIZE=5MB,
	MAXSIZE=15MB,
	FILEGROWTH=2MB
),
(	NAME='BD_AlterDB3_DATA4',
	FILENAME='C:\basedatos\BD_AlterDB3\BD_AlterDB3_DATA4.NDF',
	SIZE=5MB,
	MAXSIZE=15MB,
	FILEGROWTH=2MB
)
TO FILEGROUP GRUPO1

GO
ALTER DATABASE BD_AlterDB3
MODIFY FILEGROUP GRUPO1 DEFAULT;

GO 
ALTER DATABASE BD_AlterDB3
REMOVE FILE BD_AlterDB3_Data3;

GO
ALTER DATABASE BD_AlterDB3
MODIFY FILE
(	NAME='BD_AlterDB3_DATA1',
	SIZE=4MB,
	FILEGROWTH=3MB
);

GO
ALTER DATABASE BD_AlterDB3
MODIFY FILEGROUP GRUPO1
	READONLY;

	
GO
ALTER DATABASE BD_AlterDB3
MODIFY FILEGROUP GRUPO1
	READ_WRITE;

GO
ALTER DATABASE BD_AlterDB3
REMOVE FILE BD_AlterDB3_Data4
	
GO
ALTER DATABASE BD_AlterDB3
REMOVE FILEGROUP GRUPO1;



