USE ProyectosdeInvestigacion

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'ProyectosInv')
	DROP TABLE ProyectosInv;
	
CREATE TABLE ProyectosInv(
	CODIGOPROYECTO TINYINT NOT NULL IDENTITY,
	GUIDPROYECTO AS NEWID(),
	NOMBREPROYECTO VARCHAR(25) NOT NULL,
	PREOSUPUESTO INT ,
	FECHA_INICIO DATE DEFAULT DATEADD(DAY , -15, GETDATE())						NOT NULL,
	FECHAFIN DATE,
	
	
	CONSTRAINT PK_ProyectosInv PRIMARY KEY(CODIGOPROYECTO),
	
	CONSTRAINT CK_NOMBREPROYECTO CHECK(
		(NOMBREPROYECTO LIKE '[^0-9]%')
	),
	
	CONSTRAINT CK_PREOSUPUESTO CHECK(
		(PREOSUPUESTO > 1000)
	),
	
	CONSTRAINT CK_FECHAFIN CHECK(
		YEAR(FECHA_INICIO) = YEAR(FECHAFIN)
	
	)

);

GO
INSERT ProyectosInv (NOMBREPROYECTO, PREOSUPUESTO, FECHA_INICIO, FECHAFIN) VALUES ('PROYECTO1',2000, '10-02-2025', '10-02-2025');

GO
--SP_HELP 'ProyectosInv';

GO
SP_HELPCONSTRAINT 'ProyectosInv';
