USE ProyectosdeInvestigacion

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'FINANCIACION')
	DROP TABLE FINANCIACION;

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'PROGRAMAS')
	DROP TABLE PROGRAMAS;



IF EXISTS (SELECT * FROM SYS.tables WHERE name= 'UBICACION')
	DROP TABLE UBICACION;

IF EXISTS(SELECT * FROM SYS.tables WHERE name = 'PARTICIPA')
	DROP TABLE PARTICIPA;

IF EXISTS (SELECT * FROM SYS.types WHERE name = 'TIPODNI')
	DROP TYPE TIPODNI;

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'ProyectosInv')
	DROP TABLE ProyectosInv;
	
IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'Proyectos')
	DROP TABLE Proyectos;

GO
CREATE TYPE TIPODNI
	FROM CHAR(9) NOT NULL
	
GO
	
CREATE TABLE ProyectosInv(
	CODIGOPROYECTO TINYINT NOT NULL IDENTITY,
	GUIDPROYECTO AS NEWID(),
	NOMBREPROYECTO VARCHAR(25) NOT NULL,
	PREOSUPUESTO INT ,
	FECHA_INICIO DATE DEFAULT DATEADD(DAY , -15, GETDATE())						NOT NULL,
	FECHAFIN DATE,
	
	
	CONSTRAINT PK_ProyectosInv PRIMARY KEY(CODIGOPROYECTO),
	
	CONSTRAINT CK_NOMBREPROYECTO CHECK(
		(NOMBREPROYECTO LIKE '[^0-9]%')
	),
	
	CONSTRAINT CK_PREOSUPUESTO CHECK(
		(PREOSUPUESTO > 1000)
	),
	
	CONSTRAINT CK_FECHAFIN CHECK(
		YEAR(FECHA_INICIO) = YEAR(FECHAFIN)
	
	)

);

GO
INSERT ProyectosInv (NOMBREPROYECTO, PREOSUPUESTO, FECHA_INICIO, FECHAFIN) VALUES ('PROYECTO1',2000, '10-02-2025', '10-02-2025');

GO
--SP_HELP 'ProyectosInv';

GO
--SP_HELPCONSTRAINT 'ProyectosInv';
--SP_HELP 'CK_PREOSUPUESTO'

exec sp_rename 'ProyectosInv', 'Proyectos';

GO

--SELECT * FROM SYS.tables ProyectosdeInvestigacion;

--				E		JERCICIO 3



	
GO
	
CREATE TABLE PARTICIPA(
	DNI  TIPODNI,
	CODIGOPROYECTO TINYINT,
	FECHAINICIO DATE DEFAULT GETDATE(),
	FECHACESE DATE NULL,
	DEDICACION TINYINT,
	OBSERVACIONES TEXT
	
	CONSTRAINT PK_PARTICIPA PRIMARY KEY(DNI),
	CONSTRAINT FK_CODIGOPROYECTO FOREIGN KEY (CODIGOPROYECTO)
		REFERENCES Proyectos(CODIGOPROYECTO)
	
);



--							EJERCICIO 4
CREATE TABLE UBICACION (
	CODIGOSEDE SMALLINT IDENTITY(1,1),
	CODIGODEPARTAMENTO SMALLINT,
	ORDENANTIGUEDAD TINYINT,
	
	CONSTRAINT PK_CODIGOSEDE PRIMARY KEY (CODIGOSEDE)
) ON GRUPOPROFES;


--				EJERCICIO 5

CREATE TABLE PROGRAMAS(
	CODIGOPROGRAMA CHAR(3) DEFAULT 'P00',
	NOMBREPROGRAMA VARCHAR(25),
	
	CONSTRAINT CK_CODIGOPROGRAMA CHECK(
		(CODIGOPROGRAMA LIKE '[P,R]%[0-9]%')
	),	
	
	CONSTRAINT PK_PROGRAMAS PRIMARY KEY (CODIGOPROGRAMA),
	
);

CREATE TABLE FINANCIACION(
	CODIGOPROGRAMA CHAR(3),
	CODIGOPROYECTO TINYINT,
	FINANCIACION INT,
	
	CONSTRAINT FK_CODIGOPROGRAMA FOREIGN KEY (CODIGOPROGRAMA) REFERENCES			PROGRAMAS(CODIGOPROGRAMA),
	CONSTRAINT FK_CODIGOPROYECTO2 FOREIGN KEY (CODIGOPROYECTO) REFERENCES
		Proyectos(CODIGOPROYECTO)
)

GO
INSERT INTO PROGRAMAS (CODIGOPROGRAMA, NOMBREPROGRAMA) VALUES ('PA6', 'Hola');