
USE master;

IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'BDVideoclub')
	DROP DATABASE BDVideoclub;


	
CREATE DATABASE BDVideoclub
ON PRIMARY
(	NAME='ARCHIVOPRINCIPAL',
	FILENAME = 'C:\basedatos\BDVideoclub\ARCHIVOPRINCIPAL.MDF',
	SIZE=5MB,
	FILEGROWTH=2MB),
	
FILEGROUP DATOS_PELICULAS DEFAULT
(	NAME='DATOSPELICULAS1',
	FILENAME='C:\basedatos\BDVideoclub\DATOSPELICULAS1.NDF',
	SIZE=20MB,
	MAXSIZE=60MB,
	FILEGROWTH=10%),
(	NAME='DATOSPELICULAS2',
	FILENAME='C:\basedatos\BDVideoclub\DATOSPELICULAS2.NDF',
	SIZE=20MB,
	MAXSIZE=60MB,
	FILEGROWTH=10%);
	

USE BDVideoclub;

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'PELICULA')
	DROP TABLE PELICULA;

CREATE TABLE PELICULA(
	IDPELICULA VARCHAR(7),
	TITULO VARCHAR(20),
	AÑOPRODUCCION SMALLINT,
	GENERO	VARCHAR(15),
	DURACION	SMALLINT,
	NACIONALIDAD	VARCHAR(15)	NULL,
	
	
	CONSTRAINT CK_IDPELICULA CHECK (
		(IDPELICULA LIKE '[PF][A-Z][-][0-9][0-9][0-9][0-9]')
	),
	
	CONSTRAINT PK_PELICULA PRIMARY KEY (IDPELICULA),
	
) ON [PRIMARY];

GO

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'EJEMPLAR')
	DROP TABLE EJEMPLAR;
	
GO

CREATE TABLE EJEMPLAR(
	IDPELICULA	VARCHAR(7),
	IDEJEMPLAR	TINYINT,
	ESTADO		CHAR(1),
	FECHACOMPRA	DATE DEFAULT DATEADD(dd, -2, getDate()),
	
	
	CONSTRAINT CK_ESTADO CHECK(
		(ESTADO LIKE '[BRM]')
	),
		
	CONSTRAINT FK_IDPELICULA FOREIGN KEY (IDPELICULA) REFERENCES PELICULA(IDPELICULA),
	
	CONSTRAINT PK_EJEMPLAR PRIMARY KEY (IDPELICULA, IDEJEMPLAR)
) ON DATOS_PELICULAS;








INSERT INTO PELICULA(IDPELICULA) VALUES ('PA-1234');

INSERT INTO EJEMPLAR(IDPELICULA, IDEJEMPLAR, ESTADO) VALUES ('PA-1234',	3, 'B')

--SELECT * FROM PELICULA;
SELECT * FROM EJEMPLAR;

USE master;

