use master;

IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'BDFOTOGRAFIA')
	DROP DATABASE BDFOTOGRAFIA;
	
GO
CREATE DATABASE BDFOTOGRAFIA
ON PRIMARY
(	NAME='ArchivoPrincipal',
	FILENAME='C:\basedatos\BDFOTOGRAFIA\ArchivoPRINCIPAL.MDF',
	SIZE=15MB,
	FILEGROWTH=0MB
),
FILEGROUP DATOS_FOTOGRAFIA DEFAULT
(	NAME='DATOSFOTOS1',
	FILENAME='C:\basedatos\BDFOTOGRAFIA\DATOSFOTOS1.NDF',
	SIZE=10MB,
	MAXSIZE=50MB,
	FILEGROWTH=10%
),
(	NAME='DATOSFOTOS2',
	FILENAME='C:\basedatos\BDFOTOGRAFIA\DATOSFOTOS2.NDF',
	SIZE=10MB,
	MAXSIZE=50MB,
	FILEGROWTH=10%
)	

GO
USE BDFOTOGRAFIA;


IF EXISTS (SELECT * FROM SYS.types WHERE name='FECHA')
	DROP TYPE FECHA;

CREATE TYPE FECHA
	FROM DATETIME NULL;
	
GO

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'PROVINCIA')
	DROP TABLE PROVINCIA;

CREATE TABLE PROVINCIA (
	CODIGO	SMALLINT IDENTITY,
	NOMBRE	VARCHAR(40),
	
	CONSTRAINT PK_PROVINCIA PRIMARY KEY (CODIGO)
) ON DATOS_FOTOGRAFIA

	
IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'LOCALIDAD')
	DROP TABLE LOCALIDAD;
	
CREATE TABLE LOCALIDAD(
	CODIGO	SMALLINT IDENTITY,
	NOMBRE	VARCHAR(40),
	HABITANTES	SMALLINT 
		CONSTRAINT DF_LOCALIDAD DEFAULT 5000,
	PAGINAWEB	VARCHAR(70) NULL,
	LOCALIDAD	SMALLINT,
	
	CONSTRAINT PK_LOCALIDAD	PRIMARY KEY (CODIGO),
	CONSTRAINT FK_LOCALIDAD_PROVINCIA	FOREIGN KEY (LOCALIDAD) REFERENCES PROVINCIA(CODIGO),
	CONSTRAINT CK_HABITANTES CHECK(
		(HABITANTES > 999)
	)
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'CENTROEXPOSICION')
	DROP TABLE CENTROEXPOSICION;
	
CREATE TABLE CENTROEXPOSICION (
	CODIGO	CHAR(5),
	NOMBRE	VARCHAR(40),
	DIRECCION	VARCHAR(40),
	TELEFONO	CHAR(9),
	FECHAINAUGURACION	FECHA 
		CONSTRAINT DF_INAU DEFAULT DATEADD(YYYY,2,GETDATE()),
	METROS	FLOAT,
	PAGINAWEB	VARCHAR(70) NULL,
	LOCALIDAD	SMALLINT ,
	
	
	CONSTRAINT PK_CENTRO PRIMARY KEY (CODIGO),

	
	CONSTRAINT CK_CODIGO CHECK (
		(CODIGO LIKE '[A-Z][-][0-9][0-9][0-9]')
	),
	CONSTRAINT UQ_NOMBRE_CENTRO UNIQUE (NOMBRE),
	CONSTRAINT FK_CENTRO_LOCALIDAD FOREIGN KEY (LOCALIDAD) REFERENCES LOCALIDAD
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'SALA')
	DROP TABLE SALA;
	
CREATE TABLE SALA(
	COD_CENTROEXPOSICION CHAR(5),
	NUMERO_SALA	SMALLINT,
	METROS FLOAT,
	
		CONSTRAINT CK_COD_CENTROEXPOSICION CHECK (
		(COD_CENTROEXPOSICION LIKE '[A-Z][-][0-9][0-9][0-9]')
	),
	CONSTRAINT PK_SALA	PRIMARY KEY (COD_CENTROEXPOSICION, NUMERO_SALA),
	CONSTRAINT FK_SALA_CENTRO	FOREIGN KEY (COD_CENTROEXPOSICION) REFERENCES CENTROEXPOSICION
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'EXPOSICIONSALA')
	DROP TABLE EXPOSICIONSALA;

CREATE TABLE EXPOSICIONSALA(
	COD_CENTROEXPOSICION CHAR(5) ,
	NUMERO_SALA	SMALLINT,
	EXPOSICION	SMALLINT IDENTITY(1,5),
	FECHAINICIO FECHA
		CONSTRAINT DF_FECHAINICIO DEFAULT GETDATE(),
	FECHAFIN FECHA NULL 
		CONSTRAINT DF_FECHAFIN	DEFAULT DATEADD(DD,20,GETDATE()),
	
	
	CONSTRAINT PK_EXPOSICIONSALA PRIMARY KEY(EXPOSICION, FECHAINICIO),
	CONSTRAINT FK_EXPOSICIONSALA_SALA	FOREIGN KEY	(COD_CENTROEXPOSICION,NUMERO_SALA)
		REFERENCES SALA(COD_CENTROEXPOSICION, NUMERO_SALA)
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'EXPOSICION')
	DROP TABLE EXPOSICION;
	
CREATE TABLE EXPOSICION(
	CODIGO SMALLINT IDENTITY(1,5),
	NOMBRE	VARCHAR(40),
	TEMATICA	VARCHAR(70)
		CONSTRAINT DF_TEMATICA DEFAULT 'FIESTAS',
	DESCRIPCION	VARCHAR(70),
	
	CONSTRAINT	PK_EXPOSICION	PRIMARY KEY (CODIGO),
	CONSTRAINT	UQ_NOMBRE	UNIQUE (NOMBRE),
	CONSTRAINT	CK_TEMATICA	CHECK(
		(TEMATICA IN 
			('NATURALEZA', 'GENTES', 'FIESTAS', 'TRADICIONES', 'ESPACIOS', 'EDIIFICIOS', 'DEPORTES'))
	)
)

GO
ALTER TABLE EXPOSICIONSALA
	ADD CONSTRAINT FK_EXPOSICIONSALA_EXPOSICION	FOREIGN KEY
		(EXPOSICION) REFERENCES EXPOSICION (CODIGO)

GO

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'FOTOGRAFIA')
	DROP TABLE FOTOGRAFIA;

CREATE TABLE FOTOGRAFIA(
	CODIGO	SMALLINT IDENTITY,
	NOMBRE	VARCHAR(40),
	FECHAREALIZACION	FECHA,
	COLOR	VARCHAR(25),
	MEDIDAS	VARCHAR(40),
	EXPOSICION	SMALLINT,
	FOTOGRAFO	SMALLINT,
	
	CONSTRAINT PK_FOTOGRAFIA PRIMARY KEY(CODIGO),
	CONSTRAINT FK_FOTOGRAFIA_EXPOSICION FOREIGN KEY (EXPOSICION)
		REFERENCES EXPOSICION
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'ARTISTICA')
	DROP TABLE ARTISTICA;
	
CREATE TABLE ARTISTICA (
	CODIGO SMALLINT IDENTITY,
	ENCUADRE	VARCHAR(25),
	COMPOSICION	VARCHAR(25),
	
	CONSTRAINT PK_ARTISTICA PRIMARY KEY	(CODIGO),
	CONSTRAINT FK_ARTISTICA_FOTOGRAFIA	FOREIGN KEY (CODIGO) REFERENCES FOTOGRAFIA
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'DOCUMENTAL')
	DROP TABLE DOCUMENTAL;
	
CREATE TABLE DOCUMENTAL (
	CODIGO	SMALLINT IDENTITY,
	TIPO	VARCHAR(25),
	
	CONSTRAINT PK_DOCUMENTAL PRIMARY KEY (CODIGO),
	CONSTRAINT FK_DOCUMENTAL_FOTOGRAFIA FOREIGN KEY (CODIGO) REFERENCES FOTOGRAFIA
)

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'FOTOGRAFO')
	DROP TABLE FOTOGRAFO;

CREATE TABLE FOTOGRAFO (
	CODIGO SMALLINT IDENTITY,
	NOMBRE VARCHAR(40),
	APELLIDO1	VARCHAR(30),
	APELLIDO2	VARCHAR(30) NULL,
	FECHANACIMIENTO FECHA,
	NACIONALIDAD	VARCHAR(25),
	INFLUENCER	SMALLINT,
	
	CONSTRAINT PK_FOTOGRAFO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_INFLUENCER	FOREIGN KEY (INFLUENCER) REFERENCES FOTOGRAFO
)

GO
ALTER TABLE FOTOGRAFIA
	ADD CONSTRAINT FK_FOTOGRAFIA_FOTOGRAFO FOREIGN KEY (EXPOSICION)
		REFERENCES FOTOGRAFO;
		
GO


IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'FOTOGRAFOPREMIO')
	DROP TABLE FOTOGRAFOPREMIO;
	
CREATE TABLE FOTOGRAFOPREMIO(
	CODIGO	SMALLINT IDENTITY,
	PREMIO	VARCHAR(40),
	
	CONSTRAINT PK_PREMIO	PRIMARY KEY (CODIGO),
	CONSTRAINT FK_PREMIO_FOTOGRARFO	FOREIGN KEY (CODIGO) REFERENCES FOTOGRAFO
)
	
	
GO 

ALTER TABLE CENTROEXPOSICION
	WITH CHECK ADD CODPOSTAL	CHAR(5) CONSTRAINT DF_CODPOSTAL DEFAULT '36005' WITH VALUES,
	CONSTRAINT CK_CODPOSTAL	CHECK(
			(CODPOSTAL LIKE '[0-9][0-9][0-9][0-9][0-9]') 
		) 
GO
ALTER TABLE EXPOSICIONSALA
	DROP CONSTRAINT DF_FECHAFIN;

GO
	
ALTER TABLE EXPOSICIONSALA
	WITH CHECK ADD CONSTRAINT  DF_FECHAFIN_EXPOSICIO
		--DEFAULT   DATEADD(DD,25,GETDATE()) FOR FECHAFIN
		CHECK(
			(DATEDIFF(DAY, FECHAINICIO, FECHAFIN)) >25
			)
		
GO

CREATE TABLE ENTRADA(
	EXPOSICION SMALLINT,
	FECHAINICIO	FECHA,
	ENTRADASVENDIDAS SMALLINT,
	PRECIOENTRADA SMALLINT,
	RECAUDACION SMALLINT,
	
	CONSTRAINT PK_ENTRADA PRIMARY KEY (EXPOSICION, FECHAINICIO),
	CONSTRAINT FK_CODCENTRO FOREIGN KEY 
		(EXPOSICION, FECHAINICIO)
		REFERENCES EXPOSICIONSALA
			(EXPOSICION, FECHAINICIO)
)

CREATE TABLE LABORATORIO(
	CODIGO	SMALLINT IDENTITY(100,2),
	NOMBRE	VARCHAR(40),
	TELEFONO	CHAR(9) NULL,
	DIRECCION	VARCHAR(70),
	LOCALIDAD	SMALLINT,
	
	CONSTRAINT PK_LABO	PRIMARY KEY (CODIGO),
)

CREATE TABLE LABORATORIO_FOTOGRAFO(
	COD_FOTOGRAFO	SMALLINT,
	COD_LABORATORIO	SMALLINT,
	
	CONSTRAINT PK_LABO_FOTO PRIMARY KEY	(COD_FOTOGRAFO,COD_LABORATORIO),
	CONSTRAINT FK_COD_FOTO FOREIGN KEY (COD_FOTOGRAFO) REFERENCES
		FOTOGRAFO,
		
	CONSTRAINT FK_CODLABO	FOREIGN KEY (COD_LABORATORIO)
		REFERENCES LABORATORIO
)

GO

ALTER DATABASE BDFOTOGRAFIA
	ADD FILEGROUP	DATOS_ESTUDIOS;

GO

ALTER DATABASE BDFOTOGRAFIA
	ADD FILE(
	NAME='datosestudios1'	,
	FILENAME='C:\basedatos\BDFOTOGRAFIA\DATOSESTUDIOS1.ndf'
) to  FILEGROUP DATOS_ESTUDIOS


GO

CREATE TABLE ESTUDIO(
	CODIGO	SMALLINT,
	CIF		VARCHAR(40),
	NOMBRE	VARCHAR(40),
	LABORATORIO	SMALLINT,
	
	CONSTRAINT PK_ESTUDIO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_LABORATORIO FOREIGN KEY (LABORATORIO)
		REFERENCES LABORATORIO
) ON DATOS_ESTUDIOS;

GO

ALTER TABLE LOCALIDAD
	ALTER COLUMN PAGINAWEB VARCHAR(100)
GO
	
ALTER TABLE CENTROEXPOSICION
	DROP CONSTRAINT DF_CODPOSTAL
	
ALTER TABLE CENTROEXPOSICION
	DROP CONSTRAINT CK_CODPOSTAL	

ALTER TABLE CENTROEXPOSICION
	DROP COLUMN CODPOSTAL
	


















GO
EXEC sp_helpdb BDFOTOGRAFIA;
EXEC sp_helpfilegroup;
EXEC sp_helpfile;