IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'ProyectosdeInvestigacion')
	DROP DATABASE ProyectosdeInvestigacion;
	
	CREATE DATABASE ProyectosdeInvestigacion;
	
IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'Departamento')
	DROP TABLE Departamento;

GO	
CREATE TABLE Departamento
(	CodigoDpto	TINYINT	NOT NULL IDENTITY,
	Nombredto	varchar	NOT NULL,
	Telefono	char(9) NULL,
	Director	char(9)	NULL
	CONSTRAINT PK_CODIGODPTO PRIMARY KEY(CodigoDpto),
	CONSTRAINT UNIQUE_NOMBREDPTO UNIQUE(NOMBREDTO)
);

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'Sedes')
	DROP TABLE Sedes;
	
	
	
		
CREATE TABLE Sedes
(	CODIGOSEDE	SMALLINT	NOT NULL,
	NOMBRESEDE	VARCHAR		NOT NULL,
	CAMPUS		VARCHAR		NOT NULL,
	CONSTRAINT	PK_CODIGOSEDE PRIMARY KEY(CODIGOSEDE),
	

);

GO
--SELECT * FROM SYS.tables WHERE name = 'Sedes'
sp_help 'Sedes';

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'GRUPOS')
	DROP TABLE GRUPOS;



IF EXISTS (SELECT * FROM SYS.types WHERE name = 'TIPODNI')
	DROP TYPE TIPODNI;
	
CREATE TYPE TIPODNI
	FROM CHAR(9) NOT NULL;
	
	

	

CREATE TABLE GRUPOS
(	CODIGOGRUPO INT,
	NOMBREGRUPO	VARCHAR,
	CodDEPARTAMENTO	TINYINT NULL,
	AREACONOCIMIENTO VARCHAR NULL,
	LIDER		TIPODNI NULL,
	CONSTRAINT PK_CODIGOGRUPO PRIMARY KEY(CODIGOGRUPO),
	CONSTRAINT UNIQUE_NOMBREGRUPO	UNIQUE(NOMBREGRUPO),
	CONSTRAINT FK_CODIGOFPTO FOREIGN KEY (CodDEPARTAMENTO) REFERENCES Departamento(CodigoDpto)

	
	

)




