IF EXISTS (SELECT * FROM SYS.databases WHERE name = 'ProyectosdeInvestigacion')
	DROP DATABASE ProyectosdeInvestigacion;

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'GRUPOS')
	DROP TABLE GRUPOS;

IF EXISTS (SELECT * FROM SYS.types WHERE name = 'TIPODNI')
	DROP TYPE TIPODNI;
	
IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'Departamento')
	DROP TABLE Departamento;

IF EXISTS (SELECT * FROM SYS.tables WHERE name = 'Sedes')
	DROP TABLE Sedes;
	
	
CREATE DATABASE ProyectosdeInvestigacion;

CREATE TYPE TIPODNI
	FROM CHAR(9) NOT NULL;

CREATE TABLE Departamento
(	CodigoDpto	TINYINT	NOT NULL IDENTITY,
	Nombredto	varchar(50)	NOT NULL,
	Telefono	char(9) NULL,
	Director	char(9)	NULL
	CONSTRAINT PK_CODIGODPTO PRIMARY KEY(CodigoDpto),
	CONSTRAINT UNIQUE_NOMBREDPTO UNIQUE(NOMBREDTO),
	CONSTRAINT CK_TELEFONO  CHECK (Telefono LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
	
);
		
CREATE TABLE Sedes
(	CODIGOSEDE	SMALLINT	NOT NULL,
	NOMBRESEDE	VARCHAR		NOT NULL,
	CAMPUS		VARCHAR		NOT NULL,
	CONSTRAINT	PK_CODIGOSEDE PRIMARY KEY(CODIGOSEDE),
	

) ON [PRIMARY];

CREATE TABLE GRUPOS
(	CODIGOGRUPO INT IDENTITY(1,5), --Valor inicial , incremento 
	NOMBREGRUPO	VARCHAR,
	CodDEPARTAMENTO	TINYINT NULL,
	AREACONOCIMIENTO VARCHAR NULL,
	LIDER		TIPODNI NULL,
	CONSTRAINT PK_CODIGOGRUPO PRIMARY KEY(CODIGOGRUPO),
	CONSTRAINT UNIQUE_NOMBREGRUPO	UNIQUE(NOMBREGRUPO),
	CONSTRAINT FK_CODIGOFPTO FOREIGN KEY (CodDEPARTAMENTO) REFERENCES Departamento(CodigoDpto) -- SE puede omitir () porqué coge la clave auto
);

--SELECT * FROM SYS.tables WHERE name = 'Sedes'
exec sp_help 'Sedes'
--EXEC sp_help 'Departamento';




