IF DB_ID('BDCreateDB2') IS NOT NULL
	DROP DATABASE BDCreateDB2;
	
GO

IF DB_ID('BDCreateDB3') IS NOT NULL
	DROP DATABASE BDCreateDB3;
GO
	
IF DB_ID('Products2') IS NOT NULL
	DROP DATABASE Products2;


GO
CREATE DATABASE BDCreateDB2
ON PRIMARY
(	NAME='DBCreateDB2_Data',
	FILENAME='C:\basedatos\BDCreateDB2\DBCreateDB2_data.mdf',
	SIZE=3MB,
	FILEGROWTH = 15%
)
LOG ON
(	NAME='DBCreateDB2_log',
	FILENAME='C:\basedatos\BDCreateDB2\DBCreateDB2_LOG.ldf',
	SIZE=2MB,
	MAXSIZE=5MB,
	FILEGROWTH=15%
);

GO
CREATE DATABASE BDCreateDB3
ON PRIMARY
(	NAME='BDCreateDB3_root',
	FILENAME='C:\basedatos\BDCreateDB3\DBCreateDB3_ROOT.mdf',
	SIZE=8MB,
	MAXSIZE=9MB,
	FILEGROWTH=100KB

),
(	NAME='BDCreateDB3_data1',
	FILENAME='C:\basedatos\BDCreateDB3\DBCreateDB3_DATA1.ndf',
	SIZE=10MB,
	MAXSIZE=15MB,
	FILEGROWTH=1MB

)
LOG ON
(	NAME='BDCreateDB3_Log',
	FILENAME='C:\basedatos\BDCreateDB3\DBCreateDB3_DATA1.ldf',
	SIZE=10MB,
	MAXSIZE=15MB,
	FILEGROWTH=1MB)
GO
CREATE DATABASE Products2
