IF DB_ID('Clientes') IS NOT NULL
	DROP DATABASE Clientes
ELSE 
	PRINT ''
GO
IF EXISTS (SELECT * FROM sys.databases where name='ALUMNOS')
	PRINT ''
ELSE
	CREATE DATABASE ALUMNOS 
	
	
IF EXISTS (SELECT * FROM sys.databases where name='INSTITUTO')
	DROP DATABASE INSTITUTO
ELSE
	CREATE DATABASE INSTITUTO 