USE EMPRESANEW

IF OBJECT_ID('dbo.MayorDeDosEnteros') IS NOT NULL
	DROP PROCEDURE dbo.MayorDeDosEnteros 

GO

CREATE PROCEDURE dbo.MayorDeDosEnteros 
	(@N1 INT, @N2 INT, @MENSAJE VARCHAR(30) OUTPUT)
AS
IF (@N1 = @N2)
	SET @MENSAJE = 'Son iguales'
ELSE IF (@N1 > @N2)
	SET @MENSAJE = CAST(@N1 AS VARCHAR)
ELSE 
	SET @MENSAJE = CAST(@N2 AS VARCHAR)
	
	
DECLARE @MENSAJE2 VARCHAR(30)
EXEC dbo.MayorDeDosEnteros 5,5, @MENSAJE2 OUTPUT
SELECT @MENSAJE2

-- 2. 

GO

IF OBJECT_ID('dbo.SUMAPOSITIVO') IS NOT NULL
	DROP PROCEDURE dbo.SUMAPOSITIVO
GO

CREATE PROCEDURE dbo.SUMAPOSITIVO
	(@N1 INT, @RESULTADO INT = 1 OUTPUT)
AS 
IF (@N1 < 1 )
	SET @RESULTADO = -1
ELSE
	BEGIN 
		DECLARE @CONTADOR INT
		SET @CONTADOR = 0
		SET @RESULTADO = 0
		
		WHILE (@CONTADOR != @N1)
		BEGIN 
			SET @RESULTADO = @CONTADOR + @RESULTADO
			SET @CONTADOR = @CONTADOR +1 
		END
		
	END
	

DECLARE @RESULTADO2 INT
EXEC dbo.SUMAPOSITIVO 3, @RESULTADO2 OUTPUT
SELECT @RESULTADO2