IF OBJECT_ID('fnEdad') IS NOT NULL
	DROP FUNCTION fnEdad
	
	
GO
CREATE FUNCTION fnEdad 
(@FECHA DATE)
RETURNS INT
AS 
BEGIN

	DECLARE @EDAD TINYINT 
	
	RETURN DATEDIFF(DD, @FECHA, GETDATE()) / 365.25

END

GO
SELECT DBO.fnEdad('11-02-2003') AS EDAD

GO
SELECT Nome + ' ' + Apelido1 AS NOME , DBO.fnEdad(E.DataNacemento) AS EDAD
FROM EMPREGADO E 
INNER JOIN EMPREGADOFIXO EF ON E.NSS = EF.NSS

GO
IF OBJECT_ID('prFamiliarEdad') IS NOT NULL 
	DROP PROCEDURE prFamiliarEdad


GO
CREATE PROCEDURE prFamiliarEdad 
(
	@EDAD INT
)
AS
BEGIN
	SET NOCOUNT ON 
	
	SELECT EM.Nome + ' ' + EM.APELIDO1 AS NOME, COUNT(FA.NSS) AS CONTEO
	FROM EMPREGADO EM
	INNER JOIN FAMILIAR FA ON EM.NSS = FA.NSS_empregado
	WHERE DBO.fnEdad(FA.DataNacemento) > @EDAD
	GROUP BY EM.Nome, EM.APELIDO1
	HAVING COUNT(FA.NSS) > 1
	
	IF (@EDAD < 1 OR @EDAD > 150)
		RETURN -1

END


GO
EXEC prFamiliarEdad 22



GO
IF OBJECT_ID('fnNumEmplMayorQueEdad') IS NOT NULL
	DROP FUNCTION fnNumEmplMayorQueEdad
	
GO
CREATE FUNCTION fnNumEmplMayorQueEdad
(
	@NOME_DPTO VARCHAR(100),
	@EDAD INT
)
RETURNS INT
AS
BEGIN 
	
	--ERRORES
	IF (@NOME_DPTO NOT IN (SELECT D.NomeDepartamento FROM DEPARTAMENTO D ))
		RETURN -1
	
	IF (@EDAD < 0)
		RETURN -2

	
	DECLARE @NUM_DPTO INT
	
	SELECT @NUM_DPTO = D.NumDepartamento  FROM DEPARTAMENTO D
	WHERE NomeDepartamento = @NOME_DPTO


	return ( SELECT COUNT(*)
	FROM EMPREGADO E 
	WHERE NumDepartamentoPertenece = @NUM_DPTO AND
			DBO.fnEdad(e.DataNacemento) > @EDAD )

END



GO
IF OBJECT_ID('FNDPTO') IS NOT NULL
	DROP FUNCTION FNDPTO

GO
CREATE FUNCTION FNDPTO (@N TINYINT)
RETURNS @TABLE3 TABLE 
(
	NOMBRE_DPTO VARCHAR(100),
	NUM_PROYECTOS INT,
	NOMBRE_DIRECTOR VARCHAR(100)
)
AS
BEGIN 
	INSERT INTO @TABLE3
	SELECT D.NomeDepartamento AS DEPA, COUNT(P.NumProxecto) AS PROYECTOS, (
			SELECT NomeDepartamento FROM EMPREGADO WHERE NSS = D.NSSDirector) AS [NOME DIR]
	FROM DEPARTAMENTO D
	LEFT JOIN PROXECTO P ON P.NumDepartControla = D.NumDepartamento
	GROUP BY D.NomeDepartamento, D.NSSDirector
	HAVING COUNT(P.NumDepartControla) > @N
	
	
	RETURN
END

GO
SELECT * FROM DBO.FNDPTO(1)


GO
IF OBJECT_ID('FNDPTO2') IS NOT NULL
	DROP FUNCTION FNDPTO2


GO
CREATE FUNCTION FNDPTO2 (@N TINYINT)
RETURNS TABLE
AS 
RETURN SELECT D.NomeDepartamento AS DEPA, COUNT(P.NumProxecto) AS PROYECTOS, (
			SELECT NomeDepartamento FROM EMPREGADO WHERE NSS = D.NSSDirector) AS [NOME DIR]
	FROM DEPARTAMENTO D
	LEFT JOIN PROXECTO P ON P.NumDepartControla = D.NumDepartamento
	GROUP BY D.NomeDepartamento, D.NSSDirector
	HAVING COUNT(P.NumDepartControla) > @N
	
	