use EMPRESANEW;

if OBJECT_ID('DatosDepartamento') is not null
	drop procedure  DatosDepartamento


GO
CREATE PROCEDURE  DatosDepartamento
(
	@NAME_DPTO VARCHAR(100), @N_EMPLEADOS SMALLINT OUTPUT, 
	@N_FIJOS SMALLINT OUTPUT, @TOTAL_SALARIOS INT OUTPUT,
	@NAME_DIRECTOR VARCHAR(100) OUTPUT
)
AS
BEGIN
SET NOCOUNT ON


			

				

		
			DECLARE @NUM_DPTO TINYINT
			SELECT @NUM_DPTO = NumDepartamento
			FROM DEPARTAMENTO
			WHERE NomeDepartamento = @NAME_DPTO
		
		SELECT @N_EMPLEADOS = COUNT(*)
		FROM EMPREGADO
		WHERE NumDepartamentoPertenece = @NUM_DPTO
		
		SELECT @N_FIJOS = COUNT(*)
		FROM EMPREGADO E 
		INNER JOIN EMPREGADOFIXO EF ON E.NSS = EF.NSS
		WHERE NumDepartamentoPertenece = @NUM_DPTO
		
		SELECT @TOTAL_SALARIOS = SUM(SALARIO)
		FROM EMPREGADO E 
		INNER JOIN EMPREGADOFIXO EF ON E.NSS = EF.NSS
		WHERE NumDepartamentoPertenece = @NUM_DPTO
		
		-- COGER NOMBRE DIRECTOR
		
		DECLARE @NSS_DIRECTOR VARCHAR(15)
		
		SELECT @NSS_DIRECTOR = NSSDirector
		FROM DEPARTAMENTO 
		WHERE NomeDepartamento = @NAME_DPTO
		
		SELECT @NAME_DIRECTOR =  
			nome + ' ' + Apelido1 + ' ' + ISNULL(APELIDO2, '')
		FROM EMPREGADO
		WHERE NSS = @NSS_DIRECTOR
		
		
		-- RETURNS 
		
		IF (@NAME_DPTO NOT IN (SELECT NOMEDEPARTAMENTO
							FROM DEPARTAMENTO))
			RETURN -1
		ELSE 
			RETURN 0 
END

GO
IF OBJECT_ID('visualizardatosdepartamento') IS NOT NULL
	DROP PROCEDURE visualizardatosdepartamento


GO
CREATE PROCEDURE visualizardatosdepartamento
(@NOME_DPTO VARCHAR(100))
AS 
BEGIN
	SET NOCOUNT ON 
	
	DECLARE @N_EMPLEADOS SMALLINT
	DECLARE @N_FIJOS SMALLINT	
	DECLARE @TOTAL_SALARIOS INT
	DECLARE @NAME_DIRECTOR VARCHAR(100)

	EXEC DatosDepartamento @NOME_DPTO, @N_EMPLEADOS OUTPUT ,
						@N_FIJOS OUTPUT, @TOTAL_SALARIOS OUTPUT,
						@NAME_DIRECTOR OUTPUT
						
	PRINT('DEPARTAMENTO: ' + @NOME_DPTO)
	PRINT('DIRECTOR: ' + @NAME_DIRECTOR)
	PRINT('TOTAL SALARIO: ' + CAST(@TOTAL_SALARIOS AS VARCHAR(30)))
	PRINT('NUMERO DE EMPLEADOS FIJOS ' + CAST(@N_FIJOS AS VARCHAR(30))	 + 
			' DE UN TOTAL DE '  + CAST(@N_EMPLEADOS AS VARCHAR(30)))
					
END


EXEC visualizardatosdepartamento 'PERSOAL'

-- 5.

GO
IF OBJECT_ID('InicialEmpleados') IS NOT NULL
	DROP PROCEDURE InicialEmpleados


GO
CREATE PROCEDURE InicialEmpleados
AS
BEGIN

	DECLARE @NOME_SUPERVISOR VARCHAR(100)
	

SELECT * FROM DEPARTAMENTO
END

GO
EXEC InicialEmpleados



